CREATE TABLE IF NOT EXISTS orgs (
  id INT AUTO_INCREMENT NOT NULL UNIQUE,

  name VARCHAR(255) NOT NULL UNIQUE,
  display_name VARCHAR(255) NOT NULL UNIQUE,

  org_id VARCHAR(255) NOT NULL UNIQUE,

  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,

  PRIMARY KEY(id)
);

CREATE INDEX idx_orgs_id ON orgs(org_id);
