// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package signaling

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SignalingClient is the client API for Signaling service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignalingClient interface {
	Send(ctx context.Context, in *Body, opts ...grpc.CallOption) (*Body, error)
	ConnectStream(ctx context.Context, opts ...grpc.CallOption) (Signaling_ConnectStreamClient, error)
}

type signalingClient struct {
	cc grpc.ClientConnInterface
}

func NewSignalingClient(cc grpc.ClientConnInterface) SignalingClient {
	return &signalingClient{cc}
}

func (c *signalingClient) Send(ctx context.Context, in *Body, opts ...grpc.CallOption) (*Body, error) {
	out := new(Body)
	err := c.cc.Invoke(ctx, "/protos.Signaling/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signalingClient) ConnectStream(ctx context.Context, opts ...grpc.CallOption) (Signaling_ConnectStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Signaling_ServiceDesc.Streams[0], "/protos.Signaling/ConnectStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &signalingConnectStreamClient{stream}
	return x, nil
}

type Signaling_ConnectStreamClient interface {
	Send(*Body) error
	Recv() (*Body, error)
	grpc.ClientStream
}

type signalingConnectStreamClient struct {
	grpc.ClientStream
}

func (x *signalingConnectStreamClient) Send(m *Body) error {
	return x.ClientStream.SendMsg(m)
}

func (x *signalingConnectStreamClient) Recv() (*Body, error) {
	m := new(Body)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SignalingServer is the server API for Signaling service.
// All implementations must embed UnimplementedSignalingServer
// for forward compatibility
type SignalingServer interface {
	Send(context.Context, *Body) (*Body, error)
	ConnectStream(Signaling_ConnectStreamServer) error
	mustEmbedUnimplementedSignalingServer()
}

// UnimplementedSignalingServer must be embedded to have forward compatible implementations.
type UnimplementedSignalingServer struct {
}

func (UnimplementedSignalingServer) Send(context.Context, *Body) (*Body, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedSignalingServer) ConnectStream(Signaling_ConnectStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ConnectStream not implemented")
}
func (UnimplementedSignalingServer) mustEmbedUnimplementedSignalingServer() {}

// UnsafeSignalingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignalingServer will
// result in compilation errors.
type UnsafeSignalingServer interface {
	mustEmbedUnimplementedSignalingServer()
}

func RegisterSignalingServer(s grpc.ServiceRegistrar, srv SignalingServer) {
	s.RegisterService(&Signaling_ServiceDesc, srv)
}

func _Signaling_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Body)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignalingServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Signaling/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignalingServer).Send(ctx, req.(*Body))
	}
	return interceptor(ctx, in, info, handler)
}

func _Signaling_ConnectStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SignalingServer).ConnectStream(&signalingConnectStreamServer{stream})
}

type Signaling_ConnectStreamServer interface {
	Send(*Body) error
	Recv() (*Body, error)
	grpc.ServerStream
}

type signalingConnectStreamServer struct {
	grpc.ServerStream
}

func (x *signalingConnectStreamServer) Send(m *Body) error {
	return x.ServerStream.SendMsg(m)
}

func (x *signalingConnectStreamServer) Recv() (*Body, error) {
	m := new(Body)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Signaling_ServiceDesc is the grpc.ServiceDesc for Signaling service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Signaling_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Signaling",
	HandlerType: (*SignalingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Signaling_Send_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConnectStream",
			Handler:       _Signaling_ConnectStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protos/signaling.proto",
}
