version: '3'
services:
  redis:
    image: "redis:latest"
    container_name: wics_redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - "./data/redis:/data"

