// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.20.3
// source: runetale/runetale/v1/log_writer.proto

package logwriter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transport describes how a packet was sent/received.
type Transport int32

const (
	Transport_TRANSPORT_UNKNOWN Transport = 0
	Transport_TRANSPORT_UDP     Transport = 1
	Transport_TRANSPORT_ICE     Transport = 2
	Transport_TRANSPORT_CERF    Transport = 3
	Transport_TRANSPORT_CERF_WS Transport = 4
)

// Enum value maps for Transport.
var (
	Transport_name = map[int32]string{
		0: "TRANSPORT_UNKNOWN",
		1: "TRANSPORT_UDP",
		2: "TRANSPORT_ICE",
		3: "TRANSPORT_CERF",
		4: "TRANSPORT_CERF_WS",
	}
	Transport_value = map[string]int32{
		"TRANSPORT_UNKNOWN": 0,
		"TRANSPORT_UDP":     1,
		"TRANSPORT_ICE":     2,
		"TRANSPORT_CERF":    3,
		"TRANSPORT_CERF_WS": 4,
	}
)

func (x Transport) Enum() *Transport {
	p := new(Transport)
	*p = x
	return p
}

func (x Transport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transport) Descriptor() protoreflect.EnumDescriptor {
	return file_runetale_runetale_v1_log_writer_proto_enumTypes[0].Descriptor()
}

func (Transport) Type() protoreflect.EnumType {
	return &file_runetale_runetale_v1_log_writer_proto_enumTypes[0]
}

func (x Transport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transport.Descriptor instead.
func (Transport) EnumDescriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_log_writer_proto_rawDescGZIP(), []int{0}
}

type CerfConnEvent_State int32

const (
	CerfConnEvent_CERF_CONN_STATE_UNKNOWN      CerfConnEvent_State = 0
	CerfConnEvent_CERF_CONN_STATE_CONNECTING   CerfConnEvent_State = 1
	CerfConnEvent_CERF_CONN_STATE_CONNECTED    CerfConnEvent_State = 2
	CerfConnEvent_CERF_CONN_STATE_DISCONNECTED CerfConnEvent_State = 3
	CerfConnEvent_CERF_CONN_STATE_RECV_ERROR   CerfConnEvent_State = 4
)

// Enum value maps for CerfConnEvent_State.
var (
	CerfConnEvent_State_name = map[int32]string{
		0: "CERF_CONN_STATE_UNKNOWN",
		1: "CERF_CONN_STATE_CONNECTING",
		2: "CERF_CONN_STATE_CONNECTED",
		3: "CERF_CONN_STATE_DISCONNECTED",
		4: "CERF_CONN_STATE_RECV_ERROR",
	}
	CerfConnEvent_State_value = map[string]int32{
		"CERF_CONN_STATE_UNKNOWN":      0,
		"CERF_CONN_STATE_CONNECTING":   1,
		"CERF_CONN_STATE_CONNECTED":    2,
		"CERF_CONN_STATE_DISCONNECTED": 3,
		"CERF_CONN_STATE_RECV_ERROR":   4,
	}
)

func (x CerfConnEvent_State) Enum() *CerfConnEvent_State {
	p := new(CerfConnEvent_State)
	*p = x
	return p
}

func (x CerfConnEvent_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CerfConnEvent_State) Descriptor() protoreflect.EnumDescriptor {
	return file_runetale_runetale_v1_log_writer_proto_enumTypes[1].Descriptor()
}

func (CerfConnEvent_State) Type() protoreflect.EnumType {
	return &file_runetale_runetale_v1_log_writer_proto_enumTypes[1]
}

func (x CerfConnEvent_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CerfConnEvent_State.Descriptor instead.
func (CerfConnEvent_State) EnumDescriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_log_writer_proto_rawDescGZIP(), []int{8, 0}
}

type IceEvent_State int32

const (
	IceEvent_ICE_STATE_UNKNOWN      IceEvent_State = 0
	IceEvent_ICE_STATE_CHECKING     IceEvent_State = 1
	IceEvent_ICE_STATE_CONNECTED    IceEvent_State = 2
	IceEvent_ICE_STATE_COMPLETED    IceEvent_State = 3
	IceEvent_ICE_STATE_FAILED       IceEvent_State = 4
	IceEvent_ICE_STATE_DISCONNECTED IceEvent_State = 5
	IceEvent_ICE_STATE_CLOSED       IceEvent_State = 6
)

// Enum value maps for IceEvent_State.
var (
	IceEvent_State_name = map[int32]string{
		0: "ICE_STATE_UNKNOWN",
		1: "ICE_STATE_CHECKING",
		2: "ICE_STATE_CONNECTED",
		3: "ICE_STATE_COMPLETED",
		4: "ICE_STATE_FAILED",
		5: "ICE_STATE_DISCONNECTED",
		6: "ICE_STATE_CLOSED",
	}
	IceEvent_State_value = map[string]int32{
		"ICE_STATE_UNKNOWN":      0,
		"ICE_STATE_CHECKING":     1,
		"ICE_STATE_CONNECTED":    2,
		"ICE_STATE_COMPLETED":    3,
		"ICE_STATE_FAILED":       4,
		"ICE_STATE_DISCONNECTED": 5,
		"ICE_STATE_CLOSED":       6,
	}
)

func (x IceEvent_State) Enum() *IceEvent_State {
	p := new(IceEvent_State)
	*p = x
	return p
}

func (x IceEvent_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IceEvent_State) Descriptor() protoreflect.EnumDescriptor {
	return file_runetale_runetale_v1_log_writer_proto_enumTypes[2].Descriptor()
}

func (IceEvent_State) Type() protoreflect.EnumType {
	return &file_runetale_runetale_v1_log_writer_proto_enumTypes[2]
}

func (x IceEvent_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IceEvent_State.Descriptor instead.
func (IceEvent_State) EnumDescriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_log_writer_proto_rawDescGZIP(), []int{9, 0}
}

type FilterEvent_Result int32

const (
	FilterEvent_FILTER_RESULT_UNKNOWN FilterEvent_Result = 0
	FilterEvent_FILTER_RESULT_ACCEPT  FilterEvent_Result = 1
	FilterEvent_FILTER_RESULT_DROP    FilterEvent_Result = 2
)

// Enum value maps for FilterEvent_Result.
var (
	FilterEvent_Result_name = map[int32]string{
		0: "FILTER_RESULT_UNKNOWN",
		1: "FILTER_RESULT_ACCEPT",
		2: "FILTER_RESULT_DROP",
	}
	FilterEvent_Result_value = map[string]int32{
		"FILTER_RESULT_UNKNOWN": 0,
		"FILTER_RESULT_ACCEPT":  1,
		"FILTER_RESULT_DROP":    2,
	}
)

func (x FilterEvent_Result) Enum() *FilterEvent_Result {
	p := new(FilterEvent_Result)
	*p = x
	return p
}

func (x FilterEvent_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterEvent_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_runetale_runetale_v1_log_writer_proto_enumTypes[3].Descriptor()
}

func (FilterEvent_Result) Type() protoreflect.EnumType {
	return &file_runetale_runetale_v1_log_writer_proto_enumTypes[3]
}

func (x FilterEvent_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterEvent_Result.Descriptor instead.
func (FilterEvent_Result) EnumDescriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_log_writer_proto_rawDescGZIP(), []int{10, 0}
}

// LoglyphUploadRequest contains a batch of client debug log entries.
type LoglyphUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// session_id is the ephemeral session identifier.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// client_version is the client version string.
	ClientVersion string `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	// entries is a list of structured log entries.
	Entries []*LoglyphEntry `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *LoglyphUploadRequest) Reset() {
	*x = LoglyphUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoglyphUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoglyphUploadRequest) ProtoMessage() {}

func (x *LoglyphUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoglyphUploadRequest.ProtoReflect.Descriptor instead.
func (*LoglyphUploadRequest) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_log_writer_proto_rawDescGZIP(), []int{0}
}

func (x *LoglyphUploadRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LoglyphUploadRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *LoglyphUploadRequest) GetEntries() []*LoglyphEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// LoglyphEntry is a single client debug log entry.
type LoglyphEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// client_time is when the log was generated on the client (RFC3339Nano).
	ClientTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	// level is the log level (e.g., "info", "debug", "warn", "error").
	Level string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	// text is the log message text.
	Text string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	// payload is optional structured data (JSON-encoded).
	Payload string `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// proc_id is the process identifier (optional).
	ProcId uint32 `protobuf:"varint,5,opt,name=proc_id,json=procId,proto3" json:"proc_id,omitempty"`
	// proc_seq is the process-level sequence number (optional).
	ProcSeq uint64 `protobuf:"varint,6,opt,name=proc_seq,json=procSeq,proto3" json:"proc_seq,omitempty"`
	// v is the verbosity level (0 = normal, 1+ = verbose).
	V int32 `protobuf:"varint,7,opt,name=v,proto3" json:"v,omitempty"`
}

func (x *LoglyphEntry) Reset() {
	*x = LoglyphEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoglyphEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoglyphEntry) ProtoMessage() {}

func (x *LoglyphEntry) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoglyphEntry.ProtoReflect.Descriptor instead.
func (*LoglyphEntry) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_log_writer_proto_rawDescGZIP(), []int{1}
}

func (x *LoglyphEntry) GetClientTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ClientTime
	}
	return nil
}

func (x *LoglyphEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LoglyphEntry) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *LoglyphEntry) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *LoglyphEntry) GetProcId() uint32 {
	if x != nil {
		return x.ProcId
	}
	return 0
}

func (x *LoglyphEntry) GetProcSeq() uint64 {
	if x != nil {
		return x.ProcSeq
	}
	return 0
}

func (x *LoglyphEntry) GetV() int32 {
	if x != nil {
		return x.V
	}
	return 0
}

// LoglyphUploadResponse is returned after processing a loglyph upload.
type LoglyphUploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// accepted is the number of entries successfully stored.
	Accepted uint32 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// dropped is the number of entries dropped.
	Dropped uint32 `protobuf:"varint,2,opt,name=dropped,proto3" json:"dropped,omitempty"`
	// reason is set if any entries were dropped.
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *LoglyphUploadResponse) Reset() {
	*x = LoglyphUploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoglyphUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoglyphUploadResponse) ProtoMessage() {}

func (x *LoglyphUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoglyphUploadResponse.ProtoReflect.Descriptor instead.
func (*LoglyphUploadResponse) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_log_writer_proto_rawDescGZIP(), []int{2}
}

func (x *LoglyphUploadResponse) GetAccepted() uint32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *LoglyphUploadResponse) GetDropped() uint32 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

func (x *LoglyphUploadResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// OrbitBatchUploadRequest contains a batch of telemetry events from a client.
// Unlike the legacy OrbitBatchRequest, this does not include node_id;
// the log server identifies the stream via log_stream_id (derived from private-id).
type OrbitBatchUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// version is the client version string (e.g. "1.2.3").
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// session_id is a unique identifier for the client session.
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// events is the list of telemetry events to upload.
	Events []*OrbitEvent `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *OrbitBatchUploadRequest) Reset() {
	*x = OrbitBatchUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrbitBatchUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrbitBatchUploadRequest) ProtoMessage() {}

func (x *OrbitBatchUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrbitBatchUploadRequest.ProtoReflect.Descriptor instead.
func (*OrbitBatchUploadRequest) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_log_writer_proto_rawDescGZIP(), []int{3}
}

func (x *OrbitBatchUploadRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OrbitBatchUploadRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OrbitBatchUploadRequest) GetEvents() []*OrbitEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// OrbitBatchUploadResponse is returned after processing a batch.
type OrbitBatchUploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// accepted is the number of events successfully stored.
	Accepted uint32 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// dropped is the number of events dropped (rate limit, size limit, etc.).
	Dropped uint32 `protobuf:"varint,2,opt,name=dropped,proto3" json:"dropped,omitempty"`
	// reason is set if any events were dropped.
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *OrbitBatchUploadResponse) Reset() {
	*x = OrbitBatchUploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrbitBatchUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrbitBatchUploadResponse) ProtoMessage() {}

func (x *OrbitBatchUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrbitBatchUploadResponse.ProtoReflect.Descriptor instead.
func (*OrbitBatchUploadResponse) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_log_writer_proto_rawDescGZIP(), []int{4}
}

func (x *OrbitBatchUploadResponse) GetAccepted() uint32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *OrbitBatchUploadResponse) GetDropped() uint32 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

func (x *OrbitBatchUploadResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// OrbitEvent is a single telemetry event.
type OrbitEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// at is the client-side timestamp when the event occurred.
	At *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	// peer_hash is the first 8 bytes of SHA256(peer_public_key).
	// Used for correlation without exposing full keys.
	PeerHash []byte `protobuf:"bytes,2,opt,name=peer_hash,json=peerHash,proto3" json:"peer_hash,omitempty"`
	// region_id is the CERF region ID (if applicable).
	RegionId uint32 `protobuf:"varint,3,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	// transport is the transport type used.
	Transport Transport `protobuf:"varint,4,opt,name=transport,proto3,enum=logserver.Transport" json:"transport,omitempty"`
	// payload is one of the event types below.
	//
	// Types that are assignable to Payload:
	//
	//	*OrbitEvent_SendResult
	//	*OrbitEvent_RecvResult
	//	*OrbitEvent_CerfConn
	//	*OrbitEvent_Ice
	//	*OrbitEvent_Filter
	//	*OrbitEvent_PathTransition
	Payload isOrbitEvent_Payload `protobuf_oneof:"payload"`
}

func (x *OrbitEvent) Reset() {
	*x = OrbitEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrbitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrbitEvent) ProtoMessage() {}

func (x *OrbitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrbitEvent.ProtoReflect.Descriptor instead.
func (*OrbitEvent) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_log_writer_proto_rawDescGZIP(), []int{5}
}

func (x *OrbitEvent) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *OrbitEvent) GetPeerHash() []byte {
	if x != nil {
		return x.PeerHash
	}
	return nil
}

func (x *OrbitEvent) GetRegionId() uint32 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *OrbitEvent) GetTransport() Transport {
	if x != nil {
		return x.Transport
	}
	return Transport_TRANSPORT_UNKNOWN
}

func (m *OrbitEvent) GetPayload() isOrbitEvent_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *OrbitEvent) GetSendResult() *SendResultEvent {
	if x, ok := x.GetPayload().(*OrbitEvent_SendResult); ok {
		return x.SendResult
	}
	return nil
}

func (x *OrbitEvent) GetRecvResult() *RecvResultEvent {
	if x, ok := x.GetPayload().(*OrbitEvent_RecvResult); ok {
		return x.RecvResult
	}
	return nil
}

func (x *OrbitEvent) GetCerfConn() *CerfConnEvent {
	if x, ok := x.GetPayload().(*OrbitEvent_CerfConn); ok {
		return x.CerfConn
	}
	return nil
}

func (x *OrbitEvent) GetIce() *IceEvent {
	if x, ok := x.GetPayload().(*OrbitEvent_Ice); ok {
		return x.Ice
	}
	return nil
}

func (x *OrbitEvent) GetFilter() *FilterEvent {
	if x, ok := x.GetPayload().(*OrbitEvent_Filter); ok {
		return x.Filter
	}
	return nil
}

func (x *OrbitEvent) GetPathTransition() *PathTransitionEvent {
	if x, ok := x.GetPayload().(*OrbitEvent_PathTransition); ok {
		return x.PathTransition
	}
	return nil
}

type isOrbitEvent_Payload interface {
	isOrbitEvent_Payload()
}

type OrbitEvent_SendResult struct {
	SendResult *SendResultEvent `protobuf:"bytes,10,opt,name=send_result,json=sendResult,proto3,oneof"`
}

type OrbitEvent_RecvResult struct {
	RecvResult *RecvResultEvent `protobuf:"bytes,11,opt,name=recv_result,json=recvResult,proto3,oneof"`
}

type OrbitEvent_CerfConn struct {
	CerfConn *CerfConnEvent `protobuf:"bytes,12,opt,name=cerf_conn,json=cerfConn,proto3,oneof"`
}

type OrbitEvent_Ice struct {
	Ice *IceEvent `protobuf:"bytes,13,opt,name=ice,proto3,oneof"`
}

type OrbitEvent_Filter struct {
	Filter *FilterEvent `protobuf:"bytes,14,opt,name=filter,proto3,oneof"`
}

type OrbitEvent_PathTransition struct {
	PathTransition *PathTransitionEvent `protobuf:"bytes,15,opt,name=path_transition,json=pathTransition,proto3,oneof"`
}

func (*OrbitEvent_SendResult) isOrbitEvent_Payload() {}

func (*OrbitEvent_RecvResult) isOrbitEvent_Payload() {}

func (*OrbitEvent_CerfConn) isOrbitEvent_Payload() {}

func (*OrbitEvent_Ice) isOrbitEvent_Payload() {}

func (*OrbitEvent_Filter) isOrbitEvent_Payload() {}

func (*OrbitEvent_PathTransition) isOrbitEvent_Payload() {}

// SendResultEvent records the result of sending a packet.
type SendResultEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok    bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SendResultEvent) Reset() {
	*x = SendResultEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendResultEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResultEvent) ProtoMessage() {}

func (x *SendResultEvent) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResultEvent.ProtoReflect.Descriptor instead.
func (*SendResultEvent) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_log_writer_proto_rawDescGZIP(), []int{6}
}

func (x *SendResultEvent) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SendResultEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// RecvResultEvent records the result of receiving a packet.
type RecvResultEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// kind: 0=data, 1=keepalive, 2=handshake, etc.
	Kind int32  `protobuf:"varint,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Size uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *RecvResultEvent) Reset() {
	*x = RecvResultEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecvResultEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecvResultEvent) ProtoMessage() {}

func (x *RecvResultEvent) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecvResultEvent.ProtoReflect.Descriptor instead.
func (*RecvResultEvent) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_log_writer_proto_rawDescGZIP(), []int{7}
}

func (x *RecvResultEvent) GetKind() int32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *RecvResultEvent) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// CerfConnEvent records CERF connection state changes.
type CerfConnEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State CerfConnEvent_State `protobuf:"varint,1,opt,name=state,proto3,enum=logserver.CerfConnEvent_State" json:"state,omitempty"`
	Error string              `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CerfConnEvent) Reset() {
	*x = CerfConnEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CerfConnEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CerfConnEvent) ProtoMessage() {}

func (x *CerfConnEvent) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CerfConnEvent.ProtoReflect.Descriptor instead.
func (*CerfConnEvent) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_log_writer_proto_rawDescGZIP(), []int{8}
}

func (x *CerfConnEvent) GetState() CerfConnEvent_State {
	if x != nil {
		return x.State
	}
	return CerfConnEvent_CERF_CONN_STATE_UNKNOWN
}

func (x *CerfConnEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// IceEvent records ICE negotiation state changes.
type IceEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State         IceEvent_State `protobuf:"varint,1,opt,name=state,proto3,enum=logserver.IceEvent_State" json:"state,omitempty"`
	CandidateType string         `protobuf:"bytes,2,opt,name=candidate_type,json=candidateType,proto3" json:"candidate_type,omitempty"` // e.g. "host", "srflx", "relay"
}

func (x *IceEvent) Reset() {
	*x = IceEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IceEvent) ProtoMessage() {}

func (x *IceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IceEvent.ProtoReflect.Descriptor instead.
func (*IceEvent) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_log_writer_proto_rawDescGZIP(), []int{9}
}

func (x *IceEvent) GetState() IceEvent_State {
	if x != nil {
		return x.State
	}
	return IceEvent_ICE_STATE_UNKNOWN
}

func (x *IceEvent) GetCandidateType() string {
	if x != nil {
		return x.CandidateType
	}
	return ""
}

// FilterEvent records packet filter decisions.
type FilterEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result FilterEvent_Result `protobuf:"varint,1,opt,name=result,proto3,enum=logserver.FilterEvent_Result" json:"result,omitempty"`
	Reason string             `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // e.g. "no_matching_rule", "jailed", etc.
}

func (x *FilterEvent) Reset() {
	*x = FilterEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterEvent) ProtoMessage() {}

func (x *FilterEvent) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterEvent.ProtoReflect.Descriptor instead.
func (*FilterEvent) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_log_writer_proto_rawDescGZIP(), []int{10}
}

func (x *FilterEvent) GetResult() FilterEvent_Result {
	if x != nil {
		return x.Result
	}
	return FilterEvent_FILTER_RESULT_UNKNOWN
}

func (x *FilterEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// PathTransitionEvent records when the active path changes.
type PathTransitionEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From   Transport `protobuf:"varint,1,opt,name=from,proto3,enum=logserver.Transport" json:"from,omitempty"`
	To     Transport `protobuf:"varint,2,opt,name=to,proto3,enum=logserver.Transport" json:"to,omitempty"`
	Reason string    `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // e.g. "ice_connected", "cerf_fallback", etc.
}

func (x *PathTransitionEvent) Reset() {
	*x = PathTransitionEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PathTransitionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathTransitionEvent) ProtoMessage() {}

func (x *PathTransitionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathTransitionEvent.ProtoReflect.Descriptor instead.
func (*PathTransitionEvent) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_log_writer_proto_rawDescGZIP(), []int{11}
}

func (x *PathTransitionEvent) GetFrom() Transport {
	if x != nil {
		return x.From
	}
	return Transport_TRANSPORT_UNKNOWN
}

func (x *PathTransitionEvent) GetTo() Transport {
	if x != nil {
		return x.To
	}
	return Transport_TRANSPORT_UNKNOWN
}

func (x *PathTransitionEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// PacketFlowLogUploadRequest contains network flow statistics from a client.
// Unlike the legacy PacketFlowLogRequest, this does not include nodeId;
// the log server identifies the stream via log_stream_id (derived from private-id).
type PacketFlowLogUploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// logged_at is the timestamp when the stats were collected.
	LoggedAt string `protobuf:"bytes,1,opt,name=logged_at,json=loggedAt,proto3" json:"logged_at,omitempty"`
	// started_at is when the measurement period started.
	StartedAt string `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// ended_at is when the measurement period ended.
	EndedAt string `protobuf:"bytes,3,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	// peer_traffic records traffic between Runetale IPs (100.x.y.z <-> 100.x.y.z).
	PeerTraffic []*PacketFlowEntry `protobuf:"bytes,4,rep,name=peer_traffic,json=peerTraffic,proto3" json:"peer_traffic,omitempty"`
	// lan_traffic records traffic on explicitly advertised subnet routes.
	LanTraffic []*PacketFlowEntry `protobuf:"bytes,5,rep,name=lan_traffic,json=lanTraffic,proto3" json:"lan_traffic,omitempty"`
	// exit_node_traffic records exit node traffic (src is Runetale IP,
	// protocol/port/dst may be anonymized).
	ExitNodeTraffic []*PacketFlowEntry `protobuf:"bytes,6,rep,name=exit_node_traffic,json=exitNodeTraffic,proto3" json:"exit_node_traffic,omitempty"`
	// transport_traffic records physical WireGuard layer traffic.
	TransportTraffic []*PacketFlowEntry `protobuf:"bytes,7,rep,name=transport_traffic,json=transportTraffic,proto3" json:"transport_traffic,omitempty"`
}

func (x *PacketFlowLogUploadRequest) Reset() {
	*x = PacketFlowLogUploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketFlowLogUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketFlowLogUploadRequest) ProtoMessage() {}

func (x *PacketFlowLogUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketFlowLogUploadRequest.ProtoReflect.Descriptor instead.
func (*PacketFlowLogUploadRequest) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_log_writer_proto_rawDescGZIP(), []int{12}
}

func (x *PacketFlowLogUploadRequest) GetLoggedAt() string {
	if x != nil {
		return x.LoggedAt
	}
	return ""
}

func (x *PacketFlowLogUploadRequest) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *PacketFlowLogUploadRequest) GetEndedAt() string {
	if x != nil {
		return x.EndedAt
	}
	return ""
}

func (x *PacketFlowLogUploadRequest) GetPeerTraffic() []*PacketFlowEntry {
	if x != nil {
		return x.PeerTraffic
	}
	return nil
}

func (x *PacketFlowLogUploadRequest) GetLanTraffic() []*PacketFlowEntry {
	if x != nil {
		return x.LanTraffic
	}
	return nil
}

func (x *PacketFlowLogUploadRequest) GetExitNodeTraffic() []*PacketFlowEntry {
	if x != nil {
		return x.ExitNodeTraffic
	}
	return nil
}

func (x *PacketFlowLogUploadRequest) GetTransportTraffic() []*PacketFlowEntry {
	if x != nil {
		return x.TransportTraffic
	}
	return nil
}

// PacketFlowEntry is a single 5-tuple flow record.
type PacketFlowEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// proto is the IP protocol number (6=TCP, 17=UDP, 1=ICMPv4, 58=ICMPv6).
	Proto uint32 `protobuf:"varint,1,opt,name=proto,proto3" json:"proto,omitempty"`
	// src is the source IP address.
	Src string `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	// dst is the destination IP address.
	Dst string `protobuf:"bytes,3,opt,name=dst,proto3" json:"dst,omitempty"`
	// tx_packets is the number of transmitted packets.
	TxPackets uint64 `protobuf:"varint,4,opt,name=tx_packets,json=txPackets,proto3" json:"tx_packets,omitempty"`
	// tx_bytes is the number of transmitted bytes.
	TxBytes uint64 `protobuf:"varint,5,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	// rx_packets is the number of received packets.
	RxPackets uint64 `protobuf:"varint,6,opt,name=rx_packets,json=rxPackets,proto3" json:"rx_packets,omitempty"`
	// rx_bytes is the number of received bytes.
	RxBytes uint64 `protobuf:"varint,7,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
}

func (x *PacketFlowEntry) Reset() {
	*x = PacketFlowEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketFlowEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketFlowEntry) ProtoMessage() {}

func (x *PacketFlowEntry) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketFlowEntry.ProtoReflect.Descriptor instead.
func (*PacketFlowEntry) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_log_writer_proto_rawDescGZIP(), []int{13}
}

func (x *PacketFlowEntry) GetProto() uint32 {
	if x != nil {
		return x.Proto
	}
	return 0
}

func (x *PacketFlowEntry) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *PacketFlowEntry) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *PacketFlowEntry) GetTxPackets() uint64 {
	if x != nil {
		return x.TxPackets
	}
	return 0
}

func (x *PacketFlowEntry) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *PacketFlowEntry) GetRxPackets() uint64 {
	if x != nil {
		return x.RxPackets
	}
	return 0
}

func (x *PacketFlowEntry) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

// PacketFlowLogUploadResponse is returned after processing flow logs.
type PacketFlowLogUploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// accepted is the number of flow entries successfully stored.
	Accepted uint32 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
}

func (x *PacketFlowLogUploadResponse) Reset() {
	*x = PacketFlowLogUploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketFlowLogUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketFlowLogUploadResponse) ProtoMessage() {}

func (x *PacketFlowLogUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_log_writer_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketFlowLogUploadResponse.ProtoReflect.Descriptor instead.
func (*PacketFlowLogUploadResponse) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_log_writer_proto_rawDescGZIP(), []int{14}
}

func (x *PacketFlowLogUploadResponse) GetAccepted() uint32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

var File_runetale_runetale_v1_log_writer_proto protoreflect.FileDescriptor

var file_runetale_runetale_v1_log_writer_proto_rawDesc = []byte{
	0x0a, 0x25, 0x72, 0x75, 0x6e, 0x65, 0x74, 0x61, 0x6c, 0x65, 0x2f, 0x72, 0x75, 0x6e, 0x65, 0x74,
	0x61, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6f, 0x67, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6c, 0x6f, 0x67, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x8f, 0x01, 0x0a, 0x14, 0x4c, 0x6f, 0x67, 0x6c, 0x79, 0x70, 0x68, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x4c, 0x6f, 0x67, 0x6c, 0x79, 0x70, 0x68, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0xd1, 0x01, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x6c, 0x79, 0x70,
	0x68, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x5f,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x63, 0x49, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x63, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x53, 0x65, 0x71, 0x12, 0x0c, 0x0a, 0x01, 0x76,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x76, 0x22, 0x65, 0x0a, 0x15, 0x4c, 0x6f, 0x67,
	0x6c, 0x79, 0x70, 0x68, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x22, 0x81, 0x01, 0x0a, 0x17, 0x4f, 0x72, 0x62, 0x69, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x4f, 0x72, 0x62, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x22, 0x68, 0x0a, 0x18, 0x4f, 0x72, 0x62, 0x69, 0x74, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x64,
	0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x8e,
	0x04, 0x0a, 0x0a, 0x4f, 0x72, 0x62, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2a, 0x0a,
	0x02, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x61, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x65, 0x65,
	0x72, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x65,
	0x65, 0x72, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x09, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x3d, 0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x5f,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c,
	0x6f, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3d, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x76, 0x5f, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x6f,
	0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x63, 0x76, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x76, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x37, 0x0a, 0x09, 0x63, 0x65, 0x72, 0x66, 0x5f, 0x63, 0x6f,
	0x6e, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x65, 0x72, 0x66, 0x43, 0x6f, 0x6e, 0x6e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x48, 0x00, 0x52, 0x08, 0x63, 0x65, 0x72, 0x66, 0x43, 0x6f, 0x6e, 0x6e, 0x12, 0x27,
	0x0a, 0x03, 0x69, 0x63, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x6f,
	0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x49, 0x63, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x48, 0x00, 0x52, 0x03, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48,
	0x00, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x49, 0x0a, 0x0f, 0x70, 0x61, 0x74,
	0x68, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50,
	0x61, 0x74, 0x68, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x48, 0x00, 0x52, 0x0e, 0x70, 0x61, 0x74, 0x68, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22,
	0x37, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02,
	0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x39, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x76,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x22, 0x83, 0x02, 0x0a, 0x0d, 0x43, 0x65, 0x72, 0x66, 0x43, 0x6f, 0x6e, 0x6e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x34, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x43, 0x65, 0x72, 0x66, 0x43, 0x6f, 0x6e, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0xa5, 0x01, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x43,
	0x45, 0x52, 0x46, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x45, 0x52, 0x46,
	0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x4e,
	0x45, 0x43, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x43, 0x45, 0x52, 0x46,
	0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x4e,
	0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x20, 0x0a, 0x1c, 0x43, 0x45, 0x52, 0x46, 0x5f,
	0x43, 0x4f, 0x4e, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x44, 0x49, 0x53, 0x43, 0x4f,
	0x4e, 0x4e, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x45, 0x52,
	0x46, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x43,
	0x56, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x04, 0x22, 0x95, 0x02, 0x0a, 0x08, 0x49, 0x63,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x49, 0x63, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x61, 0x6e, 0x64, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0xb0,
	0x01, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x49, 0x43, 0x45, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x16, 0x0a, 0x12, 0x49, 0x43, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x48, 0x45,
	0x43, 0x4b, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x49, 0x43, 0x45, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x02,
	0x12, 0x17, 0x0a, 0x13, 0x49, 0x43, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x4f,
	0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x49, 0x43, 0x45,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x12,
	0x1a, 0x0a, 0x16, 0x49, 0x43, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x44, 0x49, 0x53,
	0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x05, 0x12, 0x14, 0x0a, 0x10, 0x49,
	0x43, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x44, 0x10,
	0x06, 0x22, 0xb3, 0x01, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x35, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1d, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x22, 0x55, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x19, 0x0a, 0x15, 0x46, 0x49,
	0x4c, 0x54, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x46, 0x49, 0x4c, 0x54, 0x45, 0x52, 0x5f,
	0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54, 0x10, 0x01, 0x12,
	0x16, 0x0a, 0x12, 0x46, 0x49, 0x4c, 0x54, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54,
	0x5f, 0x44, 0x52, 0x4f, 0x50, 0x10, 0x02, 0x22, 0x7d, 0x0a, 0x13, 0x50, 0x61, 0x74, 0x68, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x28,
	0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6c,
	0x6f, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x24, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x80, 0x03, 0x0a, 0x1a, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x46, 0x6c, 0x6f, 0x77, 0x4c, 0x6f, 0x67, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x41, 0x74, 0x12, 0x3d, 0x0a, 0x0c,
	0x70, 0x65, 0x65, 0x72, 0x5f, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b,
	0x70, 0x65, 0x65, 0x72, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x12, 0x3b, 0x0a, 0x0b, 0x6c,
	0x61, 0x6e, 0x5f, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x6c, 0x61,
	0x6e, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x12, 0x46, 0x0a, 0x11, 0x65, 0x78, 0x69, 0x74,
	0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x0f, 0x65, 0x78, 0x69, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63,
	0x12, 0x47, 0x0a, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x74, 0x72,
	0x61, 0x66, 0x66, 0x69, 0x63, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x6f,
	0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x46, 0x6c,
	0x6f, 0x77, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f,
	0x72, 0x74, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x22, 0xbf, 0x01, 0x0a, 0x0f, 0x50, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x73, 0x72, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x64, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x78, 0x5f, 0x70, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x78, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x78, 0x5f, 0x62, 0x79, 0x74,
	0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x74, 0x78, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x78, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x78, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73,
	0x12, 0x19, 0x0a, 0x08, 0x72, 0x78, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x72, 0x78, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x39, 0x0a, 0x1b, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x4c, 0x6f, 0x67, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x63,
	0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x2a, 0x73, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x15, 0x0a, 0x11, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x50, 0x4f, 0x52, 0x54,
	0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x52,
	0x41, 0x4e, 0x53, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x55, 0x44, 0x50, 0x10, 0x01, 0x12, 0x11, 0x0a,
	0x0d, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x49, 0x43, 0x45, 0x10, 0x02,
	0x12, 0x12, 0x0a, 0x0e, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x43, 0x45,
	0x52, 0x46, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x50, 0x4f, 0x52,
	0x54, 0x5f, 0x43, 0x45, 0x52, 0x46, 0x5f, 0x57, 0x53, 0x10, 0x04, 0x32, 0xb7, 0x02, 0x0a, 0x10,
	0x4c, 0x6f, 0x67, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x5b, 0x0a, 0x14, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x6f, 0x67, 0x6c, 0x79, 0x70,
	0x68, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1f, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x6c, 0x79, 0x70, 0x68, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6c, 0x6f, 0x67, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x6c, 0x79, 0x70, 0x68, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a,
	0x10, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4f, 0x72, 0x62, 0x69, 0x74, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x12, 0x22, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4f, 0x72,
	0x62, 0x69, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x4f, 0x72, 0x62, 0x69, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x14,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x77,
	0x4c, 0x6f, 0x67, 0x73, 0x12, 0x25, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x4c, 0x6f, 0x67, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6c, 0x6f,
	0x67, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x46, 0x6c,
	0x6f, 0x77, 0x4c, 0x6f, 0x67, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x6c, 0x6f, 0x67, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_runetale_runetale_v1_log_writer_proto_rawDescOnce sync.Once
	file_runetale_runetale_v1_log_writer_proto_rawDescData = file_runetale_runetale_v1_log_writer_proto_rawDesc
)

func file_runetale_runetale_v1_log_writer_proto_rawDescGZIP() []byte {
	file_runetale_runetale_v1_log_writer_proto_rawDescOnce.Do(func() {
		file_runetale_runetale_v1_log_writer_proto_rawDescData = protoimpl.X.CompressGZIP(file_runetale_runetale_v1_log_writer_proto_rawDescData)
	})
	return file_runetale_runetale_v1_log_writer_proto_rawDescData
}

var file_runetale_runetale_v1_log_writer_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_runetale_runetale_v1_log_writer_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_runetale_runetale_v1_log_writer_proto_goTypes = []interface{}{
	(Transport)(0),                      // 0: logserver.Transport
	(CerfConnEvent_State)(0),            // 1: logserver.CerfConnEvent.State
	(IceEvent_State)(0),                 // 2: logserver.IceEvent.State
	(FilterEvent_Result)(0),             // 3: logserver.FilterEvent.Result
	(*LoglyphUploadRequest)(nil),        // 4: logserver.LoglyphUploadRequest
	(*LoglyphEntry)(nil),                // 5: logserver.LoglyphEntry
	(*LoglyphUploadResponse)(nil),       // 6: logserver.LoglyphUploadResponse
	(*OrbitBatchUploadRequest)(nil),     // 7: logserver.OrbitBatchUploadRequest
	(*OrbitBatchUploadResponse)(nil),    // 8: logserver.OrbitBatchUploadResponse
	(*OrbitEvent)(nil),                  // 9: logserver.OrbitEvent
	(*SendResultEvent)(nil),             // 10: logserver.SendResultEvent
	(*RecvResultEvent)(nil),             // 11: logserver.RecvResultEvent
	(*CerfConnEvent)(nil),               // 12: logserver.CerfConnEvent
	(*IceEvent)(nil),                    // 13: logserver.IceEvent
	(*FilterEvent)(nil),                 // 14: logserver.FilterEvent
	(*PathTransitionEvent)(nil),         // 15: logserver.PathTransitionEvent
	(*PacketFlowLogUploadRequest)(nil),  // 16: logserver.PacketFlowLogUploadRequest
	(*PacketFlowEntry)(nil),             // 17: logserver.PacketFlowEntry
	(*PacketFlowLogUploadResponse)(nil), // 18: logserver.PacketFlowLogUploadResponse
	(*timestamppb.Timestamp)(nil),       // 19: google.protobuf.Timestamp
}
var file_runetale_runetale_v1_log_writer_proto_depIdxs = []int32{
	5,  // 0: logserver.LoglyphUploadRequest.entries:type_name -> logserver.LoglyphEntry
	19, // 1: logserver.LoglyphEntry.client_time:type_name -> google.protobuf.Timestamp
	9,  // 2: logserver.OrbitBatchUploadRequest.events:type_name -> logserver.OrbitEvent
	19, // 3: logserver.OrbitEvent.at:type_name -> google.protobuf.Timestamp
	0,  // 4: logserver.OrbitEvent.transport:type_name -> logserver.Transport
	10, // 5: logserver.OrbitEvent.send_result:type_name -> logserver.SendResultEvent
	11, // 6: logserver.OrbitEvent.recv_result:type_name -> logserver.RecvResultEvent
	12, // 7: logserver.OrbitEvent.cerf_conn:type_name -> logserver.CerfConnEvent
	13, // 8: logserver.OrbitEvent.ice:type_name -> logserver.IceEvent
	14, // 9: logserver.OrbitEvent.filter:type_name -> logserver.FilterEvent
	15, // 10: logserver.OrbitEvent.path_transition:type_name -> logserver.PathTransitionEvent
	1,  // 11: logserver.CerfConnEvent.state:type_name -> logserver.CerfConnEvent.State
	2,  // 12: logserver.IceEvent.state:type_name -> logserver.IceEvent.State
	3,  // 13: logserver.FilterEvent.result:type_name -> logserver.FilterEvent.Result
	0,  // 14: logserver.PathTransitionEvent.from:type_name -> logserver.Transport
	0,  // 15: logserver.PathTransitionEvent.to:type_name -> logserver.Transport
	17, // 16: logserver.PacketFlowLogUploadRequest.peer_traffic:type_name -> logserver.PacketFlowEntry
	17, // 17: logserver.PacketFlowLogUploadRequest.lan_traffic:type_name -> logserver.PacketFlowEntry
	17, // 18: logserver.PacketFlowLogUploadRequest.exit_node_traffic:type_name -> logserver.PacketFlowEntry
	17, // 19: logserver.PacketFlowLogUploadRequest.transport_traffic:type_name -> logserver.PacketFlowEntry
	4,  // 20: logserver.LogWriterService.UploadLoglyphEntries:input_type -> logserver.LoglyphUploadRequest
	7,  // 21: logserver.LogWriterService.UploadOrbitBatch:input_type -> logserver.OrbitBatchUploadRequest
	16, // 22: logserver.LogWriterService.UploadPacketFlowLogs:input_type -> logserver.PacketFlowLogUploadRequest
	6,  // 23: logserver.LogWriterService.UploadLoglyphEntries:output_type -> logserver.LoglyphUploadResponse
	8,  // 24: logserver.LogWriterService.UploadOrbitBatch:output_type -> logserver.OrbitBatchUploadResponse
	18, // 25: logserver.LogWriterService.UploadPacketFlowLogs:output_type -> logserver.PacketFlowLogUploadResponse
	23, // [23:26] is the sub-list for method output_type
	20, // [20:23] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_runetale_runetale_v1_log_writer_proto_init() }
func file_runetale_runetale_v1_log_writer_proto_init() {
	if File_runetale_runetale_v1_log_writer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_runetale_runetale_v1_log_writer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoglyphUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_log_writer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoglyphEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_log_writer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoglyphUploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_log_writer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrbitBatchUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_log_writer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrbitBatchUploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_log_writer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrbitEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_log_writer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendResultEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_log_writer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecvResultEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_log_writer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CerfConnEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_log_writer_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IceEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_log_writer_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_log_writer_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PathTransitionEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_log_writer_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketFlowLogUploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_log_writer_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketFlowEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_log_writer_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketFlowLogUploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_runetale_runetale_v1_log_writer_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*OrbitEvent_SendResult)(nil),
		(*OrbitEvent_RecvResult)(nil),
		(*OrbitEvent_CerfConn)(nil),
		(*OrbitEvent_Ice)(nil),
		(*OrbitEvent_Filter)(nil),
		(*OrbitEvent_PathTransition)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_runetale_runetale_v1_log_writer_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runetale_runetale_v1_log_writer_proto_goTypes,
		DependencyIndexes: file_runetale_runetale_v1_log_writer_proto_depIdxs,
		EnumInfos:         file_runetale_runetale_v1_log_writer_proto_enumTypes,
		MessageInfos:      file_runetale_runetale_v1_log_writer_proto_msgTypes,
	}.Build()
	File_runetale_runetale_v1_log_writer_proto = out.File
	file_runetale_runetale_v1_log_writer_proto_rawDesc = nil
	file_runetale_runetale_v1_log_writer_proto_goTypes = nil
	file_runetale_runetale_v1_log_writer_proto_depIdxs = nil
}
