// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.20.3
// source: runetale/runetale/v1/fleet.proto

package fleet

import (
	common "./common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFleetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc        string                  `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	ResourceIds []uint64                `protobuf:"varint,3,rep,packed,name=resourceIds,proto3" json:"resourceIds,omitempty"`
	Proto       string                  `protobuf:"bytes,4,opt,name=proto,proto3" json:"proto,omitempty"`
	Port        string                  `protobuf:"bytes,5,opt,name=port,proto3" json:"port,omitempty"`
	Type        common.DeploymentMethod `protobuf:"varint,6,opt,name=type,proto3,enum=protos.DeploymentMethod" json:"type,omitempty"`
}

func (x *CreateFleetRequest) Reset() {
	*x = CreateFleetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_fleet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFleetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFleetRequest) ProtoMessage() {}

func (x *CreateFleetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_fleet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFleetRequest.ProtoReflect.Descriptor instead.
func (*CreateFleetRequest) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFleetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFleetRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CreateFleetRequest) GetResourceIds() []uint64 {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

func (x *CreateFleetRequest) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *CreateFleetRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *CreateFleetRequest) GetType() common.DeploymentMethod {
	if x != nil {
		return x.Type
	}
	return common.DeploymentMethod(0)
}

type PatchFleetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // fleet id
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc        string   `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	ResourceIds []uint64 `protobuf:"varint,4,rep,packed,name=resourceIds,proto3" json:"resourceIds,omitempty"`
	Proto       string   `protobuf:"bytes,5,opt,name=proto,proto3" json:"proto,omitempty"`
	Port        string   `protobuf:"bytes,6,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *PatchFleetRequest) Reset() {
	*x = PatchFleetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_fleet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchFleetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchFleetRequest) ProtoMessage() {}

func (x *PatchFleetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_fleet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchFleetRequest.ProtoReflect.Descriptor instead.
func (*PatchFleetRequest) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *PatchFleetRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PatchFleetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PatchFleetRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *PatchFleetRequest) GetResourceIds() []uint64 {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

func (x *PatchFleetRequest) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *PatchFleetRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type GetFleetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetFleetRequest) Reset() {
	*x = GetFleetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_fleet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFleetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFleetRequest) ProtoMessage() {}

func (x *GetFleetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_fleet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFleetRequest.ProtoReflect.Descriptor instead.
func (*GetFleetRequest) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_fleet_proto_rawDescGZIP(), []int{2}
}

func (x *GetFleetRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Fleets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fleets []*common.Fleet `protobuf:"bytes,1,rep,name=fleets,proto3" json:"fleets,omitempty"`
}

func (x *Fleets) Reset() {
	*x = Fleets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_fleet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fleets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fleets) ProtoMessage() {}

func (x *Fleets) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_fleet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fleets.ProtoReflect.Descriptor instead.
func (*Fleets) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_fleet_proto_rawDescGZIP(), []int{3}
}

func (x *Fleets) GetFleets() []*common.Fleet {
	if x != nil {
		return x.Fleets
	}
	return nil
}

type AddNewSrcsForFleetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // fleet id
	UserIds  []uint64 `protobuf:"varint,2,rep,packed,name=userIds,proto3" json:"userIds,omitempty"`
	GroupIds []uint64 `protobuf:"varint,3,rep,packed,name=groupIds,proto3" json:"groupIds,omitempty"`
}

func (x *AddNewSrcsForFleetRequest) Reset() {
	*x = AddNewSrcsForFleetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_fleet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNewSrcsForFleetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewSrcsForFleetRequest) ProtoMessage() {}

func (x *AddNewSrcsForFleetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_fleet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewSrcsForFleetRequest.ProtoReflect.Descriptor instead.
func (*AddNewSrcsForFleetRequest) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_fleet_proto_rawDescGZIP(), []int{4}
}

func (x *AddNewSrcsForFleetRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddNewSrcsForFleetRequest) GetUserIds() []uint64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *AddNewSrcsForFleetRequest) GetGroupIds() []uint64 {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

var File_runetale_runetale_v1_fleet_proto protoreflect.FileDescriptor

var file_runetale_runetale_v1_fleet_proto_rawDesc = []byte{
	0x0a, 0x20, 0x72, 0x75, 0x6e, 0x65, 0x74, 0x61, 0x6c, 0x65, 0x2f, 0x72, 0x75, 0x6e, 0x65, 0x74,
	0x61, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x72, 0x75, 0x6e, 0x65, 0x74, 0x61, 0x6c,
	0x65, 0x2f, 0x72, 0x75, 0x6e, 0x65, 0x74, 0x61, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb6, 0x01, 0x0a, 0x12, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0b,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x44, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x22, 0x97, 0x01, 0x0a, 0x11, 0x50, 0x61, 0x74, 0x63, 0x68, 0x46, 0x6c, 0x65,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73,
	0x63, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x49, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x21, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x2f, 0x0a, 0x06, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x66, 0x6c,
	0x65, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x52, 0x06, 0x66, 0x6c, 0x65, 0x65, 0x74,
	0x73, 0x22, 0x61, 0x0a, 0x19, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x53, 0x72, 0x63, 0x73, 0x46,
	0x6f, 0x72, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x04, 0x52, 0x08, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x64, 0x73, 0x32, 0xf1, 0x01, 0x0a, 0x0c, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46,
	0x6c, 0x65, 0x65, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x22,
	0x00, 0x12, 0x38, 0x0a, 0x0a, 0x50, 0x61, 0x74, 0x63, 0x68, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x12,
	0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x61, 0x74, 0x63, 0x68, 0x46, 0x6c,
	0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x08, 0x47,
	0x65, 0x74, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x22,
	0x00, 0x12, 0x35, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x73, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x46, 0x6c, 0x65, 0x65, 0x74, 0x73, 0x22, 0x00, 0x32, 0x67, 0x0a, 0x12, 0x46, 0x6c, 0x65, 0x65,
	0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51,
	0x0a, 0x12, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x53, 0x72, 0x63, 0x73, 0x46, 0x6f, 0x72, 0x46,
	0x6c, 0x65, 0x65, 0x74, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x41, 0x64,
	0x64, 0x4e, 0x65, 0x77, 0x53, 0x72, 0x63, 0x73, 0x46, 0x6f, 0x72, 0x46, 0x6c, 0x65, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_runetale_runetale_v1_fleet_proto_rawDescOnce sync.Once
	file_runetale_runetale_v1_fleet_proto_rawDescData = file_runetale_runetale_v1_fleet_proto_rawDesc
)

func file_runetale_runetale_v1_fleet_proto_rawDescGZIP() []byte {
	file_runetale_runetale_v1_fleet_proto_rawDescOnce.Do(func() {
		file_runetale_runetale_v1_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(file_runetale_runetale_v1_fleet_proto_rawDescData)
	})
	return file_runetale_runetale_v1_fleet_proto_rawDescData
}

var file_runetale_runetale_v1_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_runetale_runetale_v1_fleet_proto_goTypes = []interface{}{
	(*CreateFleetRequest)(nil),        // 0: protos.CreateFleetRequest
	(*PatchFleetRequest)(nil),         // 1: protos.PatchFleetRequest
	(*GetFleetRequest)(nil),           // 2: protos.GetFleetRequest
	(*Fleets)(nil),                    // 3: protos.Fleets
	(*AddNewSrcsForFleetRequest)(nil), // 4: protos.AddNewSrcsForFleetRequest
	(common.DeploymentMethod)(0),      // 5: protos.DeploymentMethod
	(*common.Fleet)(nil),              // 6: protos.Fleet
	(*emptypb.Empty)(nil),             // 7: google.protobuf.Empty
}
var file_runetale_runetale_v1_fleet_proto_depIdxs = []int32{
	5, // 0: protos.CreateFleetRequest.type:type_name -> protos.DeploymentMethod
	6, // 1: protos.Fleets.fleets:type_name -> protos.Fleet
	0, // 2: protos.FleetService.CreateFleet:input_type -> protos.CreateFleetRequest
	1, // 3: protos.FleetService.PatchFleet:input_type -> protos.PatchFleetRequest
	2, // 4: protos.FleetService.GetFleet:input_type -> protos.GetFleetRequest
	7, // 5: protos.FleetService.GetFleets:input_type -> google.protobuf.Empty
	4, // 6: protos.FleetDetailService.AddNewSrcsForFleet:input_type -> protos.AddNewSrcsForFleetRequest
	6, // 7: protos.FleetService.CreateFleet:output_type -> protos.Fleet
	6, // 8: protos.FleetService.PatchFleet:output_type -> protos.Fleet
	6, // 9: protos.FleetService.GetFleet:output_type -> protos.Fleet
	3, // 10: protos.FleetService.GetFleets:output_type -> protos.Fleets
	7, // 11: protos.FleetDetailService.AddNewSrcsForFleet:output_type -> google.protobuf.Empty
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_runetale_runetale_v1_fleet_proto_init() }
func file_runetale_runetale_v1_fleet_proto_init() {
	if File_runetale_runetale_v1_fleet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_runetale_runetale_v1_fleet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFleetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_fleet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PatchFleetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_fleet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFleetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_fleet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fleets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_fleet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNewSrcsForFleetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_runetale_runetale_v1_fleet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_runetale_runetale_v1_fleet_proto_goTypes,
		DependencyIndexes: file_runetale_runetale_v1_fleet_proto_depIdxs,
		MessageInfos:      file_runetale_runetale_v1_fleet_proto_msgTypes,
	}.Build()
	File_runetale_runetale_v1_fleet_proto = out.File
	file_runetale_runetale_v1_fleet_proto_rawDesc = nil
	file_runetale_runetale_v1_fleet_proto_goTypes = nil
	file_runetale_runetale_v1_fleet_proto_depIdxs = nil
}
