// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.3
// source: runetale/runetale/v1/machine.proto

package machine

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncMachinesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsEmpty     bool          `protobuf:"varint,1,opt,name=isEmpty,proto3" json:"isEmpty,omitempty"`
	RemotePeers []*RemotePeer `protobuf:"bytes,2,rep,name=remotePeers,proto3" json:"remotePeers,omitempty"`
	Ip          string        `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`     // your ip
	Cidr        string        `protobuf:"bytes,4,opt,name=cidr,proto3" json:"cidr,omitempty"` // your cidr
}

func (x *SyncMachinesResponse) Reset() {
	*x = SyncMachinesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_machine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncMachinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMachinesResponse) ProtoMessage() {}

func (x *SyncMachinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_machine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMachinesResponse.ProtoReflect.Descriptor instead.
func (*SyncMachinesResponse) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_machine_proto_rawDescGZIP(), []int{0}
}

func (x *SyncMachinesResponse) GetIsEmpty() bool {
	if x != nil {
		return x.IsEmpty
	}
	return false
}

func (x *SyncMachinesResponse) GetRemotePeers() []*RemotePeer {
	if x != nil {
		return x.RemotePeers
	}
	return nil
}

func (x *SyncMachinesResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SyncMachinesResponse) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

type RemotePeer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteClientMachineKey string   `protobuf:"bytes,1,opt,name=remoteClientMachineKey,proto3" json:"remoteClientMachineKey,omitempty"`
	RemoteWgPubKey         string   `protobuf:"bytes,2,opt,name=remoteWgPubKey,proto3" json:"remoteWgPubKey,omitempty"`
	AllowedIPs             []string `protobuf:"bytes,3,rep,name=allowedIPs,proto3" json:"allowedIPs,omitempty"`
}

func (x *RemotePeer) Reset() {
	*x = RemotePeer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_machine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemotePeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemotePeer) ProtoMessage() {}

func (x *RemotePeer) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_machine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemotePeer.ProtoReflect.Descriptor instead.
func (*RemotePeer) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_machine_proto_rawDescGZIP(), []int{1}
}

func (x *RemotePeer) GetRemoteClientMachineKey() string {
	if x != nil {
		return x.RemoteClientMachineKey
	}
	return ""
}

func (x *RemotePeer) GetRemoteWgPubKey() string {
	if x != nil {
		return x.RemoteWgPubKey
	}
	return ""
}

func (x *RemotePeer) GetAllowedIPs() []string {
	if x != nil {
		return x.AllowedIPs
	}
	return nil
}

var File_runetale_runetale_v1_machine_proto protoreflect.FileDescriptor

var file_runetale_runetale_v1_machine_proto_rawDesc = []byte{
	0x0a, 0x22, 0x72, 0x75, 0x6e, 0x65, 0x74, 0x61, 0x6c, 0x65, 0x2f, 0x72, 0x75, 0x6e, 0x65, 0x74,
	0x61, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x1b, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d,
	0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x01, 0x0a, 0x14, 0x53, 0x79,
	0x6e, 0x63, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x34, 0x0a, 0x0b,
	0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x65, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x50, 0x65, 0x65, 0x72, 0x52, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x50, 0x65, 0x65,
	0x72, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x64, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x69, 0x64, 0x72, 0x22, 0x8c, 0x01, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x50, 0x65, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x16, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x26, 0x0a,
	0x0e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x57, 0x67, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x57, 0x67, 0x50,
	0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64,
	0x49, 0x50, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x64, 0x49, 0x50, 0x73, 0x32, 0x64, 0x0a, 0x0e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x52, 0x0a, 0x18, 0x53, 0x79, 0x6e, 0x63, 0x52,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e,
	0x2f, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_runetale_runetale_v1_machine_proto_rawDescOnce sync.Once
	file_runetale_runetale_v1_machine_proto_rawDescData = file_runetale_runetale_v1_machine_proto_rawDesc
)

func file_runetale_runetale_v1_machine_proto_rawDescGZIP() []byte {
	file_runetale_runetale_v1_machine_proto_rawDescOnce.Do(func() {
		file_runetale_runetale_v1_machine_proto_rawDescData = protoimpl.X.CompressGZIP(file_runetale_runetale_v1_machine_proto_rawDescData)
	})
	return file_runetale_runetale_v1_machine_proto_rawDescData
}

var file_runetale_runetale_v1_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_runetale_runetale_v1_machine_proto_goTypes = []interface{}{
	(*SyncMachinesResponse)(nil), // 0: protos.SyncMachinesResponse
	(*RemotePeer)(nil),           // 1: protos.RemotePeer
	(*emptypb.Empty)(nil),        // 2: google.protobuf.Empty
}
var file_runetale_runetale_v1_machine_proto_depIdxs = []int32{
	1, // 0: protos.SyncMachinesResponse.remotePeers:type_name -> protos.RemotePeer
	2, // 1: protos.MachineService.SyncRemoteMachinesConfig:input_type -> google.protobuf.Empty
	0, // 2: protos.MachineService.SyncRemoteMachinesConfig:output_type -> protos.SyncMachinesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_runetale_runetale_v1_machine_proto_init() }
func file_runetale_runetale_v1_machine_proto_init() {
	if File_runetale_runetale_v1_machine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_runetale_runetale_v1_machine_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncMachinesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_machine_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemotePeer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_runetale_runetale_v1_machine_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runetale_runetale_v1_machine_proto_goTypes,
		DependencyIndexes: file_runetale_runetale_v1_machine_proto_depIdxs,
		MessageInfos:      file_runetale_runetale_v1_machine_proto_msgTypes,
	}.Build()
	File_runetale_runetale_v1_machine_proto = out.File
	file_runetale_runetale_v1_machine_proto_rawDesc = nil
	file_runetale_runetale_v1_machine_proto_goTypes = nil
	file_runetale_runetale_v1_machine_proto_depIdxs = nil
}
