// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: notch/dotshake/v1/session.proto

package session

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SessionServiceClient is the client API for SessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionServiceClient interface {
	// Auth0ログイン後、/adminにリダイレクトした時に叩かれる
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
	// /adminにリダイレクトし、SignInのRPCを叩いた後にdotshake側で叩くRPC
	// Webからログインせずにdotshakeから直接叩く場合(ユーザーがまだ作られていない場合)はユーザーの作成、つまりSignInを行う
	SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error)
	// dotshakeのpeerの立ち上げが完了した時に叩くdotshake側で叩くRPC
	// webでStream接続しておいて立ち上げ完了を受け取る
	PeerUpComplete(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (SessionService_PeerUpCompleteClient, error)
}

type sessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionServiceClient(cc grpc.ClientConnInterface) SessionServiceClient {
	return &sessionServiceClient{cc}
}

func (c *sessionServiceClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/protos.SessionService/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) SignUp(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error) {
	out := new(SignUpResponse)
	err := c.cc.Invoke(ctx, "/protos.SessionService/SignUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) PeerUpComplete(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (SessionService_PeerUpCompleteClient, error) {
	stream, err := c.cc.NewStream(ctx, &SessionService_ServiceDesc.Streams[0], "/protos.SessionService/PeerUpComplete", opts...)
	if err != nil {
		return nil, err
	}
	x := &sessionServicePeerUpCompleteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SessionService_PeerUpCompleteClient interface {
	Recv() (*PeerUpCompleteResponse, error)
	grpc.ClientStream
}

type sessionServicePeerUpCompleteClient struct {
	grpc.ClientStream
}

func (x *sessionServicePeerUpCompleteClient) Recv() (*PeerUpCompleteResponse, error) {
	m := new(PeerUpCompleteResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SessionServiceServer is the server API for SessionService service.
// All implementations should embed UnimplementedSessionServiceServer
// for forward compatibility
type SessionServiceServer interface {
	// Auth0ログイン後、/adminにリダイレクトした時に叩かれる
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	// /adminにリダイレクトし、SignInのRPCを叩いた後にdotshake側で叩くRPC
	// Webからログインせずにdotshakeから直接叩く場合(ユーザーがまだ作られていない場合)はユーザーの作成、つまりSignInを行う
	SignUp(context.Context, *SignUpRequest) (*SignUpResponse, error)
	// dotshakeのpeerの立ち上げが完了した時に叩くdotshake側で叩くRPC
	// webでStream接続しておいて立ち上げ完了を受け取る
	PeerUpComplete(*emptypb.Empty, SessionService_PeerUpCompleteServer) error
}

// UnimplementedSessionServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSessionServiceServer struct {
}

func (UnimplementedSessionServiceServer) SignIn(context.Context, *SignInRequest) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (UnimplementedSessionServiceServer) SignUp(context.Context, *SignUpRequest) (*SignUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (UnimplementedSessionServiceServer) PeerUpComplete(*emptypb.Empty, SessionService_PeerUpCompleteServer) error {
	return status.Errorf(codes.Unimplemented, "method PeerUpComplete not implemented")
}

// UnsafeSessionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionServiceServer will
// result in compilation errors.
type UnsafeSessionServiceServer interface {
	mustEmbedUnimplementedSessionServiceServer()
}

func RegisterSessionServiceServer(s grpc.ServiceRegistrar, srv SessionServiceServer) {
	s.RegisterService(&SessionService_ServiceDesc, srv)
}

func _SessionService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.SessionService/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.SessionService/SignUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).SignUp(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_PeerUpComplete_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SessionServiceServer).PeerUpComplete(m, &sessionServicePeerUpCompleteServer{stream})
}

type SessionService_PeerUpCompleteServer interface {
	Send(*PeerUpCompleteResponse) error
	grpc.ServerStream
}

type sessionServicePeerUpCompleteServer struct {
	grpc.ServerStream
}

func (x *sessionServicePeerUpCompleteServer) Send(m *PeerUpCompleteResponse) error {
	return x.ServerStream.SendMsg(m)
}

// SessionService_ServiceDesc is the grpc.ServiceDesc for SessionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.SessionService",
	HandlerType: (*SessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignIn",
			Handler:    _SessionService_SignIn_Handler,
		},
		{
			MethodName: "SignUp",
			Handler:    _SessionService_SignUp_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PeerUpComplete",
			Handler:       _SessionService_PeerUpComplete_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "notch/dotshake/v1/session.proto",
}
