version: '3'
services:
    server:
        build:
            context: ../
            dockerfile: "docker/Dockerfile-server"
        tty: true
        ports:
            - "443:443"
        env_file: ../.env

