// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.2
// source: notch/dotshake/v1/daemon.proto

package daemon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DaemonServiceType int32

const (
	// Get the connection status between the server and Dotshake
	DaemonServiceType_ConnectionStatus DaemonServiceType = 0
)

// Enum value maps for DaemonServiceType.
var (
	DaemonServiceType_name = map[int32]string{
		0: "ConnectionStatus",
	}
	DaemonServiceType_value = map[string]int32{
		"ConnectionStatus": 0,
	}
)

func (x DaemonServiceType) Enum() *DaemonServiceType {
	p := new(DaemonServiceType)
	*p = x
	return p
}

func (x DaemonServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DaemonServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_notch_dotshake_v1_daemon_proto_enumTypes[0].Descriptor()
}

func (DaemonServiceType) Type() protoreflect.EnumType {
	return &file_notch_dotshake_v1_daemon_proto_enumTypes[0]
}

func (x DaemonServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DaemonServiceType.Descriptor instead.
func (DaemonServiceType) EnumDescriptor() ([]byte, []int) {
	return file_notch_dotshake_v1_daemon_proto_rawDescGZIP(), []int{0}
}

type DaemonServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DaemonServiceType DaemonServiceType `protobuf:"varint,1,opt,name=daemonServiceType,proto3,enum=protos.DaemonServiceType" json:"daemonServiceType,omitempty"`
}

func (x *DaemonServiceRequest) Reset() {
	*x = DaemonServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notch_dotshake_v1_daemon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DaemonServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonServiceRequest) ProtoMessage() {}

func (x *DaemonServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notch_dotshake_v1_daemon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonServiceRequest.ProtoReflect.Descriptor instead.
func (*DaemonServiceRequest) Descriptor() ([]byte, []int) {
	return file_notch_dotshake_v1_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *DaemonServiceRequest) GetDaemonServiceType() DaemonServiceType {
	if x != nil {
		return x.DaemonServiceType
	}
	return DaemonServiceType_ConnectionStatus
}

type GetConnectionStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsConnected bool `protobuf:"varint,1,opt,name=IsConnected,proto3" json:"IsConnected,omitempty"`
}

func (x *GetConnectionStatusResponse) Reset() {
	*x = GetConnectionStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notch_dotshake_v1_daemon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConnectionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionStatusResponse) ProtoMessage() {}

func (x *GetConnectionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notch_dotshake_v1_daemon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionStatusResponse) Descriptor() ([]byte, []int) {
	return file_notch_dotshake_v1_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *GetConnectionStatusResponse) GetIsConnected() bool {
	if x != nil {
		return x.IsConnected
	}
	return false
}

var File_notch_dotshake_v1_daemon_proto protoreflect.FileDescriptor

var file_notch_dotshake_v1_daemon_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6e, 0x6f, 0x74, 0x63, 0x68, 0x2f, 0x64, 0x6f, 0x74, 0x73, 0x68, 0x61, 0x6b, 0x65,
	0x2f, 0x76, 0x31, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x5f, 0x0a, 0x14, 0x44, 0x61, 0x65, 0x6d,
	0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x47, 0x0a, 0x11, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x11, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x3f, 0x0a, 0x1b, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x49, 0x73, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x49,
	0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x2a, 0x29, 0x0a, 0x11, 0x44, 0x61,
	0x65, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x10, 0x00, 0x32, 0x6f, 0x0a, 0x0d, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5e, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x64, 0x61, 0x65, 0x6d,
	0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notch_dotshake_v1_daemon_proto_rawDescOnce sync.Once
	file_notch_dotshake_v1_daemon_proto_rawDescData = file_notch_dotshake_v1_daemon_proto_rawDesc
)

func file_notch_dotshake_v1_daemon_proto_rawDescGZIP() []byte {
	file_notch_dotshake_v1_daemon_proto_rawDescOnce.Do(func() {
		file_notch_dotshake_v1_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(file_notch_dotshake_v1_daemon_proto_rawDescData)
	})
	return file_notch_dotshake_v1_daemon_proto_rawDescData
}

var file_notch_dotshake_v1_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notch_dotshake_v1_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notch_dotshake_v1_daemon_proto_goTypes = []interface{}{
	(DaemonServiceType)(0),              // 0: protos.DaemonServiceType
	(*DaemonServiceRequest)(nil),        // 1: protos.DaemonServiceRequest
	(*GetConnectionStatusResponse)(nil), // 2: protos.GetConnectionStatusResponse
}
var file_notch_dotshake_v1_daemon_proto_depIdxs = []int32{
	0, // 0: protos.DaemonServiceRequest.daemonServiceType:type_name -> protos.DaemonServiceType
	1, // 1: protos.DaemonService.GetConnectionStatus:input_type -> protos.DaemonServiceRequest
	2, // 2: protos.DaemonService.GetConnectionStatus:output_type -> protos.GetConnectionStatusResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_notch_dotshake_v1_daemon_proto_init() }
func file_notch_dotshake_v1_daemon_proto_init() {
	if File_notch_dotshake_v1_daemon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_notch_dotshake_v1_daemon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DaemonServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notch_dotshake_v1_daemon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConnectionStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notch_dotshake_v1_daemon_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notch_dotshake_v1_daemon_proto_goTypes,
		DependencyIndexes: file_notch_dotshake_v1_daemon_proto_depIdxs,
		EnumInfos:         file_notch_dotshake_v1_daemon_proto_enumTypes,
		MessageInfos:      file_notch_dotshake_v1_daemon_proto_msgTypes,
	}.Build()
	File_notch_dotshake_v1_daemon_proto = out.File
	file_notch_dotshake_v1_daemon_proto_rawDesc = nil
	file_notch_dotshake_v1_daemon_proto_goTypes = nil
	file_notch_dotshake_v1_daemon_proto_depIdxs = nil
}
