// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.1
// source: notch/dotshake/v1/admin.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMachinesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain    string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Ip        string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Cidr      string `protobuf:"bytes,3,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Host      string `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Os        string `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	IsConnect bool   `protobuf:"varint,6,opt,name=isConnect,proto3" json:"isConnect,omitempty"`
}

func (x *GetMachinesResponse) Reset() {
	*x = GetMachinesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notch_dotshake_v1_admin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMachinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMachinesResponse) ProtoMessage() {}

func (x *GetMachinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notch_dotshake_v1_admin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMachinesResponse.ProtoReflect.Descriptor instead.
func (*GetMachinesResponse) Descriptor() ([]byte, []int) {
	return file_notch_dotshake_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *GetMachinesResponse) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *GetMachinesResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *GetMachinesResponse) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *GetMachinesResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GetMachinesResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *GetMachinesResponse) GetIsConnect() bool {
	if x != nil {
		return x.IsConnect
	}
	return false
}

var File_notch_dotshake_v1_admin_proto protoreflect.FileDescriptor

var file_notch_dotshake_v1_admin_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6e, 0x6f, 0x74, 0x63, 0x68, 0x2f, 0x64, 0x6f, 0x74, 0x73, 0x68, 0x61, 0x6b, 0x65,
	0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x69, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x69, 0x73, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x32, 0x54, 0x0a, 0x0c, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61,
	0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_notch_dotshake_v1_admin_proto_rawDescOnce sync.Once
	file_notch_dotshake_v1_admin_proto_rawDescData = file_notch_dotshake_v1_admin_proto_rawDesc
)

func file_notch_dotshake_v1_admin_proto_rawDescGZIP() []byte {
	file_notch_dotshake_v1_admin_proto_rawDescOnce.Do(func() {
		file_notch_dotshake_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(file_notch_dotshake_v1_admin_proto_rawDescData)
	})
	return file_notch_dotshake_v1_admin_proto_rawDescData
}

var file_notch_dotshake_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_notch_dotshake_v1_admin_proto_goTypes = []interface{}{
	(*GetMachinesResponse)(nil), // 0: protos.GetMachinesResponse
	(*emptypb.Empty)(nil),       // 1: google.protobuf.Empty
}
var file_notch_dotshake_v1_admin_proto_depIdxs = []int32{
	1, // 0: protos.AdminService.GetMachines:input_type -> google.protobuf.Empty
	0, // 1: protos.AdminService.GetMachines:output_type -> protos.GetMachinesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notch_dotshake_v1_admin_proto_init() }
func file_notch_dotshake_v1_admin_proto_init() {
	if File_notch_dotshake_v1_admin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_notch_dotshake_v1_admin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMachinesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notch_dotshake_v1_admin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notch_dotshake_v1_admin_proto_goTypes,
		DependencyIndexes: file_notch_dotshake_v1_admin_proto_depIdxs,
		MessageInfos:      file_notch_dotshake_v1_admin_proto_msgTypes,
	}.Build()
	File_notch_dotshake_v1_admin_proto = out.File
	file_notch_dotshake_v1_admin_proto_rawDesc = nil
	file_notch_dotshake_v1_admin_proto_goTypes = nil
	file_notch_dotshake_v1_admin_proto_depIdxs = nil
}
