// telemetry.proto
//
// Runetale Telemetry (v1)
//
// 目的:
// - Wonderwall/CERF/ICE/packet filter/userspace の挙動を「理由付き」で数値化するためのイベントを定義します。
// - Phase A ではパケットの中身や 5-tuple 等の生フロー情報は送らず、軽量なイベント/集計に寄せます。
//
// 互換性:
// - 既存フィールド番号の変更/再利用は禁止（後方互換性のため）
// - フィールド追加はOK（末尾に追加推奨）
// - enum は末尾に追加（既存値の変更禁止）

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.20.3
// source: runetale/runetale/v1/telemetry.proto

package telemetry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transport は「どの経路/トランスポートで送受信したか」を表します。
type Transport int32

const (
	Transport_TRANSPORT_UNSPECIFIED Transport = 0
	Transport_TRANSPORT_CERF        Transport = 1
	Transport_TRANSPORT_ICE         Transport = 2
	Transport_TRANSPORT_UDP         Transport = 3
)

// Enum value maps for Transport.
var (
	Transport_name = map[int32]string{
		0: "TRANSPORT_UNSPECIFIED",
		1: "TRANSPORT_CERF",
		2: "TRANSPORT_ICE",
		3: "TRANSPORT_UDP",
	}
	Transport_value = map[string]int32{
		"TRANSPORT_UNSPECIFIED": 0,
		"TRANSPORT_CERF":        1,
		"TRANSPORT_ICE":         2,
		"TRANSPORT_UDP":         3,
	}
)

func (x Transport) Enum() *Transport {
	p := new(Transport)
	*p = x
	return p
}

func (x Transport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transport) Descriptor() protoreflect.EnumDescriptor {
	return file_runetale_runetale_v1_telemetry_proto_enumTypes[0].Descriptor()
}

func (Transport) Type() protoreflect.EnumType {
	return &file_runetale_runetale_v1_telemetry_proto_enumTypes[0]
}

func (x Transport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transport.Descriptor instead.
func (Transport) EnumDescriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

// PathState は endpoint の観測上の経路種別を表します。
type PathState int32

const (
	PathState_PATH_STATE_UNSPECIFIED PathState = 0
	PathState_PATH_STATE_CERF        PathState = 1
	PathState_PATH_STATE_ICE         PathState = 2
	PathState_PATH_STATE_UDP         PathState = 3
)

// Enum value maps for PathState.
var (
	PathState_name = map[int32]string{
		0: "PATH_STATE_UNSPECIFIED",
		1: "PATH_STATE_CERF",
		2: "PATH_STATE_ICE",
		3: "PATH_STATE_UDP",
	}
	PathState_value = map[string]int32{
		"PATH_STATE_UNSPECIFIED": 0,
		"PATH_STATE_CERF":        1,
		"PATH_STATE_ICE":         2,
		"PATH_STATE_UDP":         3,
	}
)

func (x PathState) Enum() *PathState {
	p := new(PathState)
	*p = x
	return p
}

func (x PathState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PathState) Descriptor() protoreflect.EnumDescriptor {
	return file_runetale_runetale_v1_telemetry_proto_enumTypes[1].Descriptor()
}

func (PathState) Type() protoreflect.EnumType {
	return &file_runetale_runetale_v1_telemetry_proto_enumTypes[1]
}

func (x PathState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PathState.Descriptor instead.
func (PathState) EnumDescriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

// RecvKind は受信したメッセージ種別です。
type RecvKind int32

const (
	RecvKind_RECV_KIND_UNSPECIFIED RecvKind = 0
	RecvKind_RECV_KIND_WIREGUARD   RecvKind = 1
	RecvKind_RECV_KIND_RUNE        RecvKind = 2
)

// Enum value maps for RecvKind.
var (
	RecvKind_name = map[int32]string{
		0: "RECV_KIND_UNSPECIFIED",
		1: "RECV_KIND_WIREGUARD",
		2: "RECV_KIND_RUNE",
	}
	RecvKind_value = map[string]int32{
		"RECV_KIND_UNSPECIFIED": 0,
		"RECV_KIND_WIREGUARD":   1,
		"RECV_KIND_RUNE":        2,
	}
)

func (x RecvKind) Enum() *RecvKind {
	p := new(RecvKind)
	*p = x
	return p
}

func (x RecvKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecvKind) Descriptor() protoreflect.EnumDescriptor {
	return file_runetale_runetale_v1_telemetry_proto_enumTypes[2].Descriptor()
}

func (RecvKind) Type() protoreflect.EnumType {
	return &file_runetale_runetale_v1_telemetry_proto_enumTypes[2]
}

func (x RecvKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecvKind.Descriptor instead.
func (RecvKind) EnumDescriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

type CerfConnEvent_CerfConnState int32

const (
	CerfConnEvent_CERF_CONN_STATE_UNSPECIFIED     CerfConnEvent_CerfConnState = 0
	CerfConnEvent_CERF_CONN_STATE_CONNECTED       CerfConnEvent_CerfConnState = 1
	CerfConnEvent_CERF_CONN_STATE_RECONNECTED     CerfConnEvent_CerfConnState = 2
	CerfConnEvent_CERF_CONN_STATE_RECV_ERROR      CerfConnEvent_CerfConnState = 3
	CerfConnEvent_CERF_CONN_STATE_SEND_ERROR      CerfConnEvent_CerfConnState = 4
	CerfConnEvent_CERF_CONN_STATE_REGION_FAILOVER CerfConnEvent_CerfConnState = 5
)

// Enum value maps for CerfConnEvent_CerfConnState.
var (
	CerfConnEvent_CerfConnState_name = map[int32]string{
		0: "CERF_CONN_STATE_UNSPECIFIED",
		1: "CERF_CONN_STATE_CONNECTED",
		2: "CERF_CONN_STATE_RECONNECTED",
		3: "CERF_CONN_STATE_RECV_ERROR",
		4: "CERF_CONN_STATE_SEND_ERROR",
		5: "CERF_CONN_STATE_REGION_FAILOVER",
	}
	CerfConnEvent_CerfConnState_value = map[string]int32{
		"CERF_CONN_STATE_UNSPECIFIED":     0,
		"CERF_CONN_STATE_CONNECTED":       1,
		"CERF_CONN_STATE_RECONNECTED":     2,
		"CERF_CONN_STATE_RECV_ERROR":      3,
		"CERF_CONN_STATE_SEND_ERROR":      4,
		"CERF_CONN_STATE_REGION_FAILOVER": 5,
	}
)

func (x CerfConnEvent_CerfConnState) Enum() *CerfConnEvent_CerfConnState {
	p := new(CerfConnEvent_CerfConnState)
	*p = x
	return p
}

func (x CerfConnEvent_CerfConnState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CerfConnEvent_CerfConnState) Descriptor() protoreflect.EnumDescriptor {
	return file_runetale_runetale_v1_telemetry_proto_enumTypes[3].Descriptor()
}

func (CerfConnEvent_CerfConnState) Type() protoreflect.EnumType {
	return &file_runetale_runetale_v1_telemetry_proto_enumTypes[3]
}

func (x CerfConnEvent_CerfConnState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CerfConnEvent_CerfConnState.Descriptor instead.
func (CerfConnEvent_CerfConnState) EnumDescriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_telemetry_proto_rawDescGZIP(), []int{6, 0}
}

type IceEvent_IceState int32

const (
	IceEvent_ICE_STATE_UNSPECIFIED     IceEvent_IceState = 0
	IceEvent_ICE_STATE_AGENT_START     IceEvent_IceState = 1
	IceEvent_ICE_STATE_CONN_UP         IceEvent_IceState = 2
	IceEvent_ICE_STATE_CONN_DOWN       IceEvent_IceState = 3
	IceEvent_ICE_STATE_SEND_ERROR      IceEvent_IceState = 4
	IceEvent_ICE_STATE_ENDPOINT_UPDATE IceEvent_IceState = 5
)

// Enum value maps for IceEvent_IceState.
var (
	IceEvent_IceState_name = map[int32]string{
		0: "ICE_STATE_UNSPECIFIED",
		1: "ICE_STATE_AGENT_START",
		2: "ICE_STATE_CONN_UP",
		3: "ICE_STATE_CONN_DOWN",
		4: "ICE_STATE_SEND_ERROR",
		5: "ICE_STATE_ENDPOINT_UPDATE",
	}
	IceEvent_IceState_value = map[string]int32{
		"ICE_STATE_UNSPECIFIED":     0,
		"ICE_STATE_AGENT_START":     1,
		"ICE_STATE_CONN_UP":         2,
		"ICE_STATE_CONN_DOWN":       3,
		"ICE_STATE_SEND_ERROR":      4,
		"ICE_STATE_ENDPOINT_UPDATE": 5,
	}
)

func (x IceEvent_IceState) Enum() *IceEvent_IceState {
	p := new(IceEvent_IceState)
	*p = x
	return p
}

func (x IceEvent_IceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IceEvent_IceState) Descriptor() protoreflect.EnumDescriptor {
	return file_runetale_runetale_v1_telemetry_proto_enumTypes[4].Descriptor()
}

func (IceEvent_IceState) Type() protoreflect.EnumType {
	return &file_runetale_runetale_v1_telemetry_proto_enumTypes[4]
}

func (x IceEvent_IceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IceEvent_IceState.Descriptor instead.
func (IceEvent_IceState) EnumDescriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_telemetry_proto_rawDescGZIP(), []int{7, 0}
}

type FilterDecision_FilterResult int32

const (
	FilterDecision_FILTER_RESULT_UNSPECIFIED FilterDecision_FilterResult = 0
	FilterDecision_FILTER_RESULT_ACCEPT      FilterDecision_FilterResult = 1
	FilterDecision_FILTER_RESULT_DROP        FilterDecision_FilterResult = 2
	FilterDecision_FILTER_RESULT_DROP_SILENT FilterDecision_FilterResult = 3
)

// Enum value maps for FilterDecision_FilterResult.
var (
	FilterDecision_FilterResult_name = map[int32]string{
		0: "FILTER_RESULT_UNSPECIFIED",
		1: "FILTER_RESULT_ACCEPT",
		2: "FILTER_RESULT_DROP",
		3: "FILTER_RESULT_DROP_SILENT",
	}
	FilterDecision_FilterResult_value = map[string]int32{
		"FILTER_RESULT_UNSPECIFIED": 0,
		"FILTER_RESULT_ACCEPT":      1,
		"FILTER_RESULT_DROP":        2,
		"FILTER_RESULT_DROP_SILENT": 3,
	}
)

func (x FilterDecision_FilterResult) Enum() *FilterDecision_FilterResult {
	p := new(FilterDecision_FilterResult)
	*p = x
	return p
}

func (x FilterDecision_FilterResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterDecision_FilterResult) Descriptor() protoreflect.EnumDescriptor {
	return file_runetale_runetale_v1_telemetry_proto_enumTypes[5].Descriptor()
}

func (FilterDecision_FilterResult) Type() protoreflect.EnumType {
	return &file_runetale_runetale_v1_telemetry_proto_enumTypes[5]
}

func (x FilterDecision_FilterResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterDecision_FilterResult.Descriptor instead.
func (FilterDecision_FilterResult) EnumDescriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_telemetry_proto_rawDescGZIP(), []int{8, 0}
}

// TelemetryBatchRequest はクライアントから server へイベントをまとめて送るリクエストです。
type TelemetryBatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// runetale node id
	NodeId uint64 `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	// 1プロセス/1接続期間の識別子（クライアント側で生成）
	SessionId string `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	// client build/version 情報（任意）
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// イベント本体
	Events []*TelemetryEvent `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *TelemetryBatchRequest) Reset() {
	*x = TelemetryBatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_telemetry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TelemetryBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryBatchRequest) ProtoMessage() {}

func (x *TelemetryBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_telemetry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryBatchRequest.ProtoReflect.Descriptor instead.
func (*TelemetryBatchRequest) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryBatchRequest) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *TelemetryBatchRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TelemetryBatchRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TelemetryBatchRequest) GetEvents() []*TelemetryEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type TelemetryBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// server が受理したイベント数
	Accepted uint32 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// server 側で破棄したイベント数（サイズ/レート/検証失敗など）
	Dropped uint32 `protobuf:"varint,2,opt,name=dropped,proto3" json:"dropped,omitempty"`
	// 代表的な理由（任意）
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *TelemetryBatchResponse) Reset() {
	*x = TelemetryBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_telemetry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TelemetryBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryBatchResponse) ProtoMessage() {}

func (x *TelemetryBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_telemetry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryBatchResponse.ProtoReflect.Descriptor instead.
func (*TelemetryBatchResponse) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryBatchResponse) GetAccepted() uint32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *TelemetryBatchResponse) GetDropped() uint32 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

func (x *TelemetryBatchResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// TelemetryEvent は1レコードのイベントです。
// 共通フィールド + oneof(種類別ペイロード) で表現します。
type TelemetryEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// イベント発生時刻（クライアント側）
	At *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	// peer識別子（生鍵を送らない）。HMAC等で匿名化した固定長のハッシュを想定。
	PeerHash []byte `protobuf:"bytes,2,opt,name=peerHash,proto3" json:"peerHash,omitempty"`
	// CERF のリージョンID（該当する場合のみ）。unknown は 0。
	RegionId uint32 `protobuf:"varint,3,opt,name=regionId,proto3" json:"regionId,omitempty"`
	// このイベントに紐づくトランスポート（該当する場合のみ）
	Transport Transport `protobuf:"varint,4,opt,name=transport,proto3,enum=protos.Transport" json:"transport,omitempty"`
	// 種類別の詳細
	//
	// Types that are assignable to Payload:
	//
	//	*TelemetryEvent_PathTransition
	//	*TelemetryEvent_SendResult
	//	*TelemetryEvent_RecvResult
	//	*TelemetryEvent_CerfConn
	//	*TelemetryEvent_Ice
	//	*TelemetryEvent_Filter
	Payload isTelemetryEvent_Payload `protobuf_oneof:"payload"`
}

func (x *TelemetryEvent) Reset() {
	*x = TelemetryEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_telemetry_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TelemetryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEvent) ProtoMessage() {}

func (x *TelemetryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_telemetry_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEvent.ProtoReflect.Descriptor instead.
func (*TelemetryEvent) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *TelemetryEvent) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *TelemetryEvent) GetPeerHash() []byte {
	if x != nil {
		return x.PeerHash
	}
	return nil
}

func (x *TelemetryEvent) GetRegionId() uint32 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *TelemetryEvent) GetTransport() Transport {
	if x != nil {
		return x.Transport
	}
	return Transport_TRANSPORT_UNSPECIFIED
}

func (m *TelemetryEvent) GetPayload() isTelemetryEvent_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *TelemetryEvent) GetPathTransition() *PathTransition {
	if x, ok := x.GetPayload().(*TelemetryEvent_PathTransition); ok {
		return x.PathTransition
	}
	return nil
}

func (x *TelemetryEvent) GetSendResult() *SendResult {
	if x, ok := x.GetPayload().(*TelemetryEvent_SendResult); ok {
		return x.SendResult
	}
	return nil
}

func (x *TelemetryEvent) GetRecvResult() *RecvResult {
	if x, ok := x.GetPayload().(*TelemetryEvent_RecvResult); ok {
		return x.RecvResult
	}
	return nil
}

func (x *TelemetryEvent) GetCerfConn() *CerfConnEvent {
	if x, ok := x.GetPayload().(*TelemetryEvent_CerfConn); ok {
		return x.CerfConn
	}
	return nil
}

func (x *TelemetryEvent) GetIce() *IceEvent {
	if x, ok := x.GetPayload().(*TelemetryEvent_Ice); ok {
		return x.Ice
	}
	return nil
}

func (x *TelemetryEvent) GetFilter() *FilterDecision {
	if x, ok := x.GetPayload().(*TelemetryEvent_Filter); ok {
		return x.Filter
	}
	return nil
}

type isTelemetryEvent_Payload interface {
	isTelemetryEvent_Payload()
}

type TelemetryEvent_PathTransition struct {
	PathTransition *PathTransition `protobuf:"bytes,10,opt,name=path_transition,json=pathTransition,proto3,oneof"`
}

type TelemetryEvent_SendResult struct {
	SendResult *SendResult `protobuf:"bytes,11,opt,name=send_result,json=sendResult,proto3,oneof"`
}

type TelemetryEvent_RecvResult struct {
	RecvResult *RecvResult `protobuf:"bytes,12,opt,name=recv_result,json=recvResult,proto3,oneof"`
}

type TelemetryEvent_CerfConn struct {
	CerfConn *CerfConnEvent `protobuf:"bytes,13,opt,name=cerf_conn,json=cerfConn,proto3,oneof"`
}

type TelemetryEvent_Ice struct {
	Ice *IceEvent `protobuf:"bytes,14,opt,name=ice,proto3,oneof"`
}

type TelemetryEvent_Filter struct {
	Filter *FilterDecision `protobuf:"bytes,15,opt,name=filter,proto3,oneof"`
}

func (*TelemetryEvent_PathTransition) isTelemetryEvent_Payload() {}

func (*TelemetryEvent_SendResult) isTelemetryEvent_Payload() {}

func (*TelemetryEvent_RecvResult) isTelemetryEvent_Payload() {}

func (*TelemetryEvent_CerfConn) isTelemetryEvent_Payload() {}

func (*TelemetryEvent_Ice) isTelemetryEvent_Payload() {}

func (*TelemetryEvent_Filter) isTelemetryEvent_Payload() {}

// PathTransition は経路の選択/切替を表します。
type PathTransition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From PathState `protobuf:"varint,1,opt,name=from,proto3,enum=protos.PathState" json:"from,omitempty"`
	To   PathState `protobuf:"varint,2,opt,name=to,proto3,enum=protos.PathState" json:"to,omitempty"`
	// 切替理由（機械集計可能な短い文字列を推奨）
	// 例: "force_cerf", "recv_confirmed", "no_recvwg_timeout", "trial_prefer_ice", "cerf_fail_fallback"
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// 追加情報（任意）
	Detail string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *PathTransition) Reset() {
	*x = PathTransition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_telemetry_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PathTransition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathTransition) ProtoMessage() {}

func (x *PathTransition) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_telemetry_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathTransition.ProtoReflect.Descriptor instead.
func (*PathTransition) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *PathTransition) GetFrom() PathState {
	if x != nil {
		return x.From
	}
	return PathState_PATH_STATE_UNSPECIFIED
}

func (x *PathTransition) GetTo() PathState {
	if x != nil {
		return x.To
	}
	return PathState_PATH_STATE_UNSPECIFIED
}

func (x *PathTransition) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PathTransition) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// SendResult は送信の結果（成功/失敗）を表します。
type SendResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// 送信したバイト数（payload長）
	Bytes uint32 `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	// エラー分類（任意）
	ErrCode string `protobuf:"bytes,3,opt,name=errCode,proto3" json:"errCode,omitempty"`
}

func (x *SendResult) Reset() {
	*x = SendResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_telemetry_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResult) ProtoMessage() {}

func (x *SendResult) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_telemetry_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResult.ProtoReflect.Descriptor instead.
func (*SendResult) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *SendResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SendResult) GetBytes() uint32 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *SendResult) GetErrCode() string {
	if x != nil {
		return x.ErrCode
	}
	return ""
}

// RecvResult は受信処理の結果を表します。
type RecvResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok      bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Kind    RecvKind `protobuf:"varint,2,opt,name=kind,proto3,enum=protos.RecvKind" json:"kind,omitempty"`
	Bytes   uint32   `protobuf:"varint,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	ErrCode string   `protobuf:"bytes,4,opt,name=errCode,proto3" json:"errCode,omitempty"`
}

func (x *RecvResult) Reset() {
	*x = RecvResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_telemetry_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecvResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecvResult) ProtoMessage() {}

func (x *RecvResult) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_telemetry_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecvResult.ProtoReflect.Descriptor instead.
func (*RecvResult) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *RecvResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RecvResult) GetKind() RecvKind {
	if x != nil {
		return x.Kind
	}
	return RecvKind_RECV_KIND_UNSPECIFIED
}

func (x *RecvResult) GetBytes() uint32 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *RecvResult) GetErrCode() string {
	if x != nil {
		return x.ErrCode
	}
	return ""
}

// CerfConnEvent は CERF の接続/再接続/エラー等の状態変化を表します。
type CerfConnEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// cerfhttp.Client の connGen（再接続ごとに増える）
	ConnGen int32                       `protobuf:"varint,1,opt,name=connGen,proto3" json:"connGen,omitempty"`
	State   CerfConnEvent_CerfConnState `protobuf:"varint,2,opt,name=state,proto3,enum=protos.CerfConnEvent_CerfConnState" json:"state,omitempty"`
	Detail  string                      `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *CerfConnEvent) Reset() {
	*x = CerfConnEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_telemetry_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CerfConnEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CerfConnEvent) ProtoMessage() {}

func (x *CerfConnEvent) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_telemetry_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CerfConnEvent.ProtoReflect.Descriptor instead.
func (*CerfConnEvent) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_telemetry_proto_rawDescGZIP(), []int{6}
}

func (x *CerfConnEvent) GetConnGen() int32 {
	if x != nil {
		return x.ConnGen
	}
	return 0
}

func (x *CerfConnEvent) GetState() CerfConnEvent_CerfConnState {
	if x != nil {
		return x.State
	}
	return CerfConnEvent_CERF_CONN_STATE_UNSPECIFIED
}

func (x *CerfConnEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// IceEvent は ICE の状態変化（候補更新/接続確立/エラー等）を表します。
type IceEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State  IceEvent_IceState `protobuf:"varint,1,opt,name=state,proto3,enum=protos.IceEvent_IceState" json:"state,omitempty"`
	Detail string            `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *IceEvent) Reset() {
	*x = IceEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_telemetry_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IceEvent) ProtoMessage() {}

func (x *IceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_telemetry_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IceEvent.ProtoReflect.Descriptor instead.
func (*IceEvent) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_telemetry_proto_rawDescGZIP(), []int{7}
}

func (x *IceEvent) GetState() IceEvent_IceState {
	if x != nil {
		return x.State
	}
	return IceEvent_ICE_STATE_UNSPECIFIED
}

func (x *IceEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// FilterDecision は packet filter の判定（accept/drop）を表します。
// Phase A では最小情報のみ（ルール名/理由/方向）を想定。
type FilterDecision struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result FilterDecision_FilterResult `protobuf:"varint,1,opt,name=result,proto3,enum=protos.FilterDecision_FilterResult" json:"result,omitempty"`
	Reason string                      `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *FilterDecision) Reset() {
	*x = FilterDecision{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runetale_runetale_v1_telemetry_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterDecision) ProtoMessage() {}

func (x *FilterDecision) ProtoReflect() protoreflect.Message {
	mi := &file_runetale_runetale_v1_telemetry_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterDecision.ProtoReflect.Descriptor instead.
func (*FilterDecision) Descriptor() ([]byte, []int) {
	return file_runetale_runetale_v1_telemetry_proto_rawDescGZIP(), []int{8}
}

func (x *FilterDecision) GetResult() FilterDecision_FilterResult {
	if x != nil {
		return x.Result
	}
	return FilterDecision_FILTER_RESULT_UNSPECIFIED
}

func (x *FilterDecision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_runetale_runetale_v1_telemetry_proto protoreflect.FileDescriptor

var file_runetale_runetale_v1_telemetry_proto_rawDesc = []byte{
	0x0a, 0x24, 0x72, 0x75, 0x6e, 0x65, 0x74, 0x61, 0x6c, 0x65, 0x2f, 0x72, 0x75, 0x6e, 0x65, 0x74,
	0x61, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x97, 0x01, 0x0a, 0x15, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x06, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x66, 0x0a, 0x16, 0x54, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x64, 0x72, 0x6f, 0x70, 0x70, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x22, 0xef, 0x03, 0x0a, 0x0e, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x02, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x61, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x65, 0x65, 0x72, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x70, 0x65, 0x65, 0x72, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x09,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x41, 0x0a, 0x0f, 0x70, 0x61, 0x74,
	0x68, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x61, 0x74, 0x68,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0e, 0x70, 0x61,
	0x74, 0x68, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x0b,
	0x73, 0x65, 0x6e, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x35, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x76, 0x5f, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x52, 0x65, 0x63, 0x76, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x0a,
	0x72, 0x65, 0x63, 0x76, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x34, 0x0a, 0x09, 0x63, 0x65,
	0x72, 0x66, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x65, 0x72, 0x66, 0x43, 0x6f, 0x6e, 0x6e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x08, 0x63, 0x65, 0x72, 0x66, 0x43, 0x6f, 0x6e, 0x6e,
	0x12, 0x24, 0x0a, 0x03, 0x69, 0x63, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x49, 0x63, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48,
	0x00, 0x52, 0x03, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x48, 0x00,
	0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x22, 0x8a, 0x01, 0x0a, 0x0e, 0x50, 0x61, 0x74, 0x68, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x61,
	0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x21, 0x0a,
	0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x02, 0x74, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x22, 0x4c, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x14,
	0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x72,
	0x0a, 0x0a, 0x52, 0x65, 0x63, 0x76, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x24, 0x0a, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x52, 0x65, 0x63, 0x76, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x22, 0xd4, 0x02, 0x0a, 0x0d, 0x43, 0x65, 0x72, 0x66, 0x43, 0x6f, 0x6e, 0x6e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x47, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x47, 0x65, 0x6e, 0x12, 0x39,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x65, 0x72, 0x66, 0x43, 0x6f, 0x6e, 0x6e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x65, 0x72, 0x66, 0x43, 0x6f, 0x6e, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x22, 0xd5, 0x01, 0x0a, 0x0d, 0x43, 0x65, 0x72, 0x66, 0x43, 0x6f, 0x6e, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x1b, 0x43, 0x45, 0x52, 0x46, 0x5f, 0x43, 0x4f, 0x4e, 0x4e,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x1d, 0x0a, 0x19, 0x43, 0x45, 0x52, 0x46, 0x5f, 0x43, 0x4f, 0x4e,
	0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x45,
	0x44, 0x10, 0x01, 0x12, 0x1f, 0x0a, 0x1b, 0x43, 0x45, 0x52, 0x46, 0x5f, 0x43, 0x4f, 0x4e, 0x4e,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54,
	0x45, 0x44, 0x10, 0x02, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x45, 0x52, 0x46, 0x5f, 0x43, 0x4f, 0x4e,
	0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x43, 0x56, 0x5f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x03, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x45, 0x52, 0x46, 0x5f, 0x43, 0x4f, 0x4e,
	0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x45, 0x4e, 0x44, 0x5f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x04, 0x12, 0x23, 0x0a, 0x1f, 0x43, 0x45, 0x52, 0x46, 0x5f, 0x43, 0x4f, 0x4e,
	0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x4f, 0x4e, 0x5f, 0x46,
	0x41, 0x49, 0x4c, 0x4f, 0x56, 0x45, 0x52, 0x10, 0x05, 0x22, 0xff, 0x01, 0x0a, 0x08, 0x49, 0x63,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x49,
	0x63, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x49, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22,
	0xa9, 0x01, 0x0a, 0x08, 0x49, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x15,
	0x49, 0x43, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x49, 0x43, 0x45, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x45, 0x5f, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54,
	0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x49, 0x43, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x43, 0x4f, 0x4e, 0x4e, 0x5f, 0x55, 0x50, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x49, 0x43, 0x45,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x5f, 0x44, 0x4f, 0x57, 0x4e,
	0x10, 0x03, 0x12, 0x18, 0x0a, 0x14, 0x49, 0x43, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f,
	0x53, 0x45, 0x4e, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x04, 0x12, 0x1d, 0x0a, 0x19,
	0x49, 0x43, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x45, 0x4e, 0x44, 0x50, 0x4f, 0x49,
	0x4e, 0x54, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x05, 0x22, 0xe5, 0x01, 0x0a, 0x0e,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x3b,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x44, 0x65,
	0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x22, 0x7e, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x19, 0x46, 0x49, 0x4c, 0x54, 0x45, 0x52, 0x5f, 0x52, 0x45,
	0x53, 0x55, 0x4c, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x46, 0x49, 0x4c, 0x54, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x53,
	0x55, 0x4c, 0x54, 0x5f, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12,
	0x46, 0x49, 0x4c, 0x54, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x44, 0x52,
	0x4f, 0x50, 0x10, 0x02, 0x12, 0x1d, 0x0a, 0x19, 0x46, 0x49, 0x4c, 0x54, 0x45, 0x52, 0x5f, 0x52,
	0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x44, 0x52, 0x4f, 0x50, 0x5f, 0x53, 0x49, 0x4c, 0x45, 0x4e,
	0x54, 0x10, 0x03, 0x2a, 0x60, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x19, 0x0a, 0x15, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x54,
	0x52, 0x41, 0x4e, 0x53, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x43, 0x45, 0x52, 0x46, 0x10, 0x01, 0x12,
	0x11, 0x0a, 0x0d, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x50, 0x4f, 0x52, 0x54, 0x5f, 0x49, 0x43, 0x45,
	0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x50, 0x4f, 0x52, 0x54, 0x5f,
	0x55, 0x44, 0x50, 0x10, 0x03, 0x2a, 0x64, 0x0a, 0x09, 0x50, 0x61, 0x74, 0x68, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x50, 0x41, 0x54, 0x48, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x13,
	0x0a, 0x0f, 0x50, 0x41, 0x54, 0x48, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x45, 0x52,
	0x46, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x41, 0x54, 0x48, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x45, 0x5f, 0x49, 0x43, 0x45, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x41, 0x54, 0x48, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x44, 0x50, 0x10, 0x03, 0x2a, 0x52, 0x0a, 0x08, 0x52,
	0x65, 0x63, 0x76, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x19, 0x0a, 0x15, 0x52, 0x45, 0x43, 0x56, 0x5f,
	0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45, 0x43, 0x56, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f,
	0x57, 0x49, 0x52, 0x45, 0x47, 0x55, 0x41, 0x52, 0x44, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x52,
	0x45, 0x43, 0x56, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x52, 0x55, 0x4e, 0x45, 0x10, 0x02, 0x42,
	0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_runetale_runetale_v1_telemetry_proto_rawDescOnce sync.Once
	file_runetale_runetale_v1_telemetry_proto_rawDescData = file_runetale_runetale_v1_telemetry_proto_rawDesc
)

func file_runetale_runetale_v1_telemetry_proto_rawDescGZIP() []byte {
	file_runetale_runetale_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_runetale_runetale_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(file_runetale_runetale_v1_telemetry_proto_rawDescData)
	})
	return file_runetale_runetale_v1_telemetry_proto_rawDescData
}

var file_runetale_runetale_v1_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_runetale_runetale_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_runetale_runetale_v1_telemetry_proto_goTypes = []interface{}{
	(Transport)(0),                   // 0: protos.Transport
	(PathState)(0),                   // 1: protos.PathState
	(RecvKind)(0),                    // 2: protos.RecvKind
	(CerfConnEvent_CerfConnState)(0), // 3: protos.CerfConnEvent.CerfConnState
	(IceEvent_IceState)(0),           // 4: protos.IceEvent.IceState
	(FilterDecision_FilterResult)(0), // 5: protos.FilterDecision.FilterResult
	(*TelemetryBatchRequest)(nil),    // 6: protos.TelemetryBatchRequest
	(*TelemetryBatchResponse)(nil),   // 7: protos.TelemetryBatchResponse
	(*TelemetryEvent)(nil),           // 8: protos.TelemetryEvent
	(*PathTransition)(nil),           // 9: protos.PathTransition
	(*SendResult)(nil),               // 10: protos.SendResult
	(*RecvResult)(nil),               // 11: protos.RecvResult
	(*CerfConnEvent)(nil),            // 12: protos.CerfConnEvent
	(*IceEvent)(nil),                 // 13: protos.IceEvent
	(*FilterDecision)(nil),           // 14: protos.FilterDecision
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
}
var file_runetale_runetale_v1_telemetry_proto_depIdxs = []int32{
	8,  // 0: protos.TelemetryBatchRequest.events:type_name -> protos.TelemetryEvent
	15, // 1: protos.TelemetryEvent.at:type_name -> google.protobuf.Timestamp
	0,  // 2: protos.TelemetryEvent.transport:type_name -> protos.Transport
	9,  // 3: protos.TelemetryEvent.path_transition:type_name -> protos.PathTransition
	10, // 4: protos.TelemetryEvent.send_result:type_name -> protos.SendResult
	11, // 5: protos.TelemetryEvent.recv_result:type_name -> protos.RecvResult
	12, // 6: protos.TelemetryEvent.cerf_conn:type_name -> protos.CerfConnEvent
	13, // 7: protos.TelemetryEvent.ice:type_name -> protos.IceEvent
	14, // 8: protos.TelemetryEvent.filter:type_name -> protos.FilterDecision
	1,  // 9: protos.PathTransition.from:type_name -> protos.PathState
	1,  // 10: protos.PathTransition.to:type_name -> protos.PathState
	2,  // 11: protos.RecvResult.kind:type_name -> protos.RecvKind
	3,  // 12: protos.CerfConnEvent.state:type_name -> protos.CerfConnEvent.CerfConnState
	4,  // 13: protos.IceEvent.state:type_name -> protos.IceEvent.IceState
	5,  // 14: protos.FilterDecision.result:type_name -> protos.FilterDecision.FilterResult
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_runetale_runetale_v1_telemetry_proto_init() }
func file_runetale_runetale_v1_telemetry_proto_init() {
	if File_runetale_runetale_v1_telemetry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_runetale_runetale_v1_telemetry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TelemetryBatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_telemetry_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TelemetryBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_telemetry_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TelemetryEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_telemetry_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PathTransition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_telemetry_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_telemetry_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecvResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_telemetry_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CerfConnEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_telemetry_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IceEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runetale_runetale_v1_telemetry_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterDecision); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_runetale_runetale_v1_telemetry_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*TelemetryEvent_PathTransition)(nil),
		(*TelemetryEvent_SendResult)(nil),
		(*TelemetryEvent_RecvResult)(nil),
		(*TelemetryEvent_CerfConn)(nil),
		(*TelemetryEvent_Ice)(nil),
		(*TelemetryEvent_Filter)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_runetale_runetale_v1_telemetry_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_runetale_runetale_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_runetale_runetale_v1_telemetry_proto_depIdxs,
		EnumInfos:         file_runetale_runetale_v1_telemetry_proto_enumTypes,
		MessageInfos:      file_runetale_runetale_v1_telemetry_proto_msgTypes,
	}.Build()
	File_runetale_runetale_v1_telemetry_proto = out.File
	file_runetale_runetale_v1_telemetry_proto_rawDesc = nil
	file_runetale_runetale_v1_telemetry_proto_goTypes = nil
	file_runetale_runetale_v1_telemetry_proto_depIdxs = nil
}
